- .gitignore
- Dockerfile
- Makefile
- OWNERS
Needed for https://jira.coreos.com/browse/LOG-186
> fix LOG-186. Makefile and Dockerfile for openshift

- pkg/stub/handler.go
> clean up a bit

- pkg/apis/elasticsearch/v1alpha1/types.go
- pkg/k8shandler/configmaps.go
- pkg/k8shandler/configuration_tmpl.go
- pkg/k8shandler/defaults.go
- pkg/k8shandler/desirednodestate.go
- pkg/k8shandler/render_config.go
@ewolinetz can you help me with populating `defaults.go`?
> [log203] Source ES cluster configuration from CR

- pkg/k8shandler/desirednodestate.go
Resolves https://jira.coreos.com/browse/LOG-246
> Adding label for openshift-tuned operator es profile

- Makefile
- README.md
- hack/common
- hack/cr.yaml
- hack/deploy-image.sh
- hack/deploy-setup.sh
- hack/deploy.sh
- hack/prometheus-operator-crd-cluster-roles.yaml
- hack/prometheus-rules.yaml
- hack/undeploy.sh
- manifests/05-deployment.yaml
- manifests/image-references
Add Make targets to simplify deployment
> add Make targets to deploy operator

- cmd/elasticsearch-operator/main.go
dynamically construct log level list from logrus
do not duplicate code from logrus
> dynamically construct log level list from logrus

- Makefile
- README.md
- hack/cr.yaml
- hack/test-e2e.sh
- manifests/01-service-account.yaml
- manifests/02-role.yaml
- manifests/03-role-bindings.yaml
- manifests/04-crd.yaml
- manifests/05-deployment.yaml
- pkg/apis/elasticsearch/v1alpha1/types.go
- pkg/k8shandler/cluster.go
- pkg/k8shandler/util.go
- test/e2e/elasticsearch_test.go
Addresses https://jira.coreos.com/browse/LOG-248
> Managed spec

- pkg/k8shandler/deployment.go
4.0 fix of https://bugzilla.redhat.com/show_bug.cgi?id=1655675
> fix 1655675. Deployment progress deadline

- hack/deploy-image.sh
port forwarding can take a while to come up
> port forwarding can take a while to come up

- pkg/k8shandler/defaults.go
Default to shared_ops to fix https://jira.coreos.com/browse/LOG-312
> fix LOG-312. Default kibana.index_mode to shared_ops

- Makefile
- OWNERS
* Update the OWNERS file to remove @jwforres 
*  format code on build
> update OWNERS and always format on build

- hack/cr.yaml
- pkg/k8shandler/cluster.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/desirednodestate.go
- pkg/k8shandler/nodetypefactory.go
- pkg/k8shandler/service_monitor.go
- pkg/k8shandler/statefulset.go
- pkg/k8shandler/status.go
- pkg/stub/handler.go
This is to address https://bugzilla.redhat.com/show_bug.cgi?id=1664497
> Separate create upgrade

- pkg/apis/elasticsearch/v1alpha1/types.go
- pkg/apis/elasticsearch/v1alpha1/zz_generated.deepcopy.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/desirednodestate.go
- pkg/k8shandler/util.go
Make sure that all nodes share the same image, but can differ in resource limits and requests
> All nodes have to be created from the same Image

- pkg/k8shandler/service_monitor.go
- pkg/k8shandler/services.go
> Bugfix: added name to es svc port and configured that name for service monitor

- README.md
dummy commit to force rebuild upon merge
> dummy commit to force rebuild upon merge

- Makefile
- README.md
- hack/test-e2e.sh
- test/e2e/elasticsearch_test.go
This PR:
* fixes e2e to match the CR
* makes changes to make it compatible with CI
> fix e2e test and prepare for execution by CI

- pkg/k8shandler/desirednodestate.go
Bug tracker https://jira.coreos.com/browse/LOG-333
> fix wrong envar on elasticsearch deployment

- files/prometheus_alerts.yml
> Update Alerting rules

- hack/test-e2e.sh
- manifests/02-role.yaml
Follow up to https://github.com/openshift/elasticsearch-operator/pull/76
> Adding missing roles for eo sa fixing failing e2e tests

- README.md
> Fix diagram link

- Dockerfile
- controller-manifests/elasticsearch-operator.package.yaml
- controller-manifests/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
- controller-manifests/elasticsearches.crd.yaml
This PR adds manifest for marketplace
> add manifest for marketplace

- Dockerfile
remove EO from CVO build pipeline
> remove EO from CVO build pipeline

- Dockerfile
- Dockerfile.rhel7
- controller-manifests/elasticsearch-operator.package.yaml
- controller-manifests/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
- controller-manifests/elasticsearches.crd.yaml
This PR reverts the revert of marketplace manifest
> Add Marketplace manifest

- pkg/k8shandler/status.go
Seen here: https://github.com/openshift/cluster-logging-operator/pull/112#issuecomment-476469211
> fix referencing the wrong spec for status

- pkg/k8shandler/deployment.go
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1692796
> Bug 1692796 - fixing refreshing node before state determines upgrade is needed

- pkg/k8shandler/common.go
- pkg/k8shandler/status.go
Addresses https://jira.coreos.com/browse/LOG-365
> updating component to be elasticsearch instead of cr name

- pkg/apis/elasticsearch/v1/types.go
- pkg/k8shandler/cluster.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/nodetypefactory.go
- pkg/k8shandler/statefulset.go
- pkg/k8shandler/status.go
- pkg/k8shandler/util.go
- pkg/utils/utils.go
- test/e2e/elasticsearch_test.go
- test/utils/utils.go
generate UUIDs for the different es nodes, verify that they are not changed after being initially created/used
> Bug 1691148 - assign uuid for ES nodes

- Makefile
- README.md
- hack/build-image.sh
- hack/common
- hack/deploy-image.sh
Support building UBI based images, and images that need the
private repo for rpms.
Make it easier to build the image and push to a deployed
cluster with the logging images.
> UBI support; allow image build and push with oal logging

- pkg/k8shandler/elasticsearch.go
- pkg/k8shandler/status.go
Addresses https://jira.coreos.com/browse/LOG-339?focusedCommentId=83169&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-83169
> fixing watermark status checks

- pkg/k8shandler/cluster.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/elasticsearch.go
- pkg/k8shandler/nodetypefactory.go
- pkg/k8shandler/statefulset.go
- pkg/k8shandler/status.go
The operator should be able to update pods in Pending/Failed phase.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1699015
> Enable the operator to perform unassisted updates

- pkg/k8shandler/defaults.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/statefulset.go
- pkg/k8shandler/util.go
- pkg/k8shandler/util_test.go
```
panic: assignment to entry in nil map [recovered]
panic: assignment to entry in nil map
```
> Bug 1707323: Operator may attempt to write into nil map

- manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
- manifests/elasticsearch-operator.package.yaml
This PR fixes up the CSV for z stream release to adhere to ART and OLM expectations
> Bug 1717623 - fix CSV for OLM and ART

- manifests/art.yaml
Fix art.yaml to point to the correct package file.
> Bug 1717627: fix art.yml ref to package.yaml

- pkg/k8shandler/common.go
- pkg/k8shandler/common_test.go
- pkg/k8shandler/defaults.go
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1710404
> Bug 1710404 - Removing setting a default cpu limit

- pkg/k8shandler/common.go
- pkg/k8shandler/common_test.go
- pkg/k8shandler/util.go
Replaces https://github.com/openshift/cluster-logging-operator/pull/198
> LOG-411 All pods are allocated to linux nodes

- manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
- manifests/4.2/elasticsearch-operator.v4.2.0.clusterserviceversion.yaml
- manifests/elasticsearch-operator.package.yaml
This addresses issue @bparees saw with deploying via elasticsearch operator csv.
> Fixing redundancyPolicy field level in alm-examples

- pkg/apis/logging/v1/elasticsearch_types.go
- pkg/apis/logging/v1/zz_generated.deepcopy.go
- pkg/k8shandler/common.go
- pkg/k8shandler/common_test.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/statefulset.go
- pkg/k8shandler/util.go
- pkg/k8shandler/util_test.go
Addresses https://jira.coreos.com/browse/LOG-392
> Adding support to set tolerations for es nodes and common

- Makefile
- pkg/k8shandler/common_test.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/deployment_test.go
- pkg/k8shandler/elasticsearch.go
- pkg/logger/logger.go
bug 1740447. Only update the cpu/memory limit if they are greater then zero
https://bugzilla.redhat.com/show_bug.cgi?id=1740447
> Bug 1740447: Only set resource limits when value is greater then zero

- manifests/4.3/elasticsearch-operator.v4.3.0.clusterserviceversion.yaml
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1768936
> Bug 1768936: set minikube version

- pkg/k8shandler/rbac.go
https://bugzilla.redhat.com/show_bug.cgi?id=1765807
https://issues.jboss.org/browse/OSSM-100
Image pavolloffay/es-operator:rbac-subjects
pavolloffay/es-operator:4.2.rbac-subjects
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
> Bug 1765807: Add subject per ES instance to es-proxy cluster role binding

- hack/test-e2e-wip.sh
- hack/test-e2e.sh
Fix failure to install prometheus CRDs
> fix prometheus crd location

- pkg/k8shandler/configmaps.go
- pkg/k8shandler/defaults.go
- test/e2e/elasticsearch_test.go
Add annotation to allow switching the log appender in testing
cc @ewolinetz @igor-karpukhin
> add logAppender annotation for development

- pkg/k8shandler/deployment.go
- pkg/k8shandler/statefulset.go
Manual cherry-pick of https://github.com/openshift/elasticsearch-operator/pull/202
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1789261
> Bug 1789261: Dont restart cluster just because EO restarted

- Makefile
- hack/test-e2e.sh
- hack/testing/utils
- hack/vendor/olm-test-script/e2e-olm.sh
Update to make operand sourced from ci imagestream
> update deployment to use images from defined imagestream

- manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1799051
> Bug 1799051: Add OLM annotations for ui hints

- Makefile
- hack/cr.yaml
- manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
- pkg/apis/logging/v1/elasticsearch_types.go
- pkg/indexmanagement/converters.go
- pkg/indexmanagement/converters_test.go
- pkg/indexmanagement/indexmanagement_suite_test.go
- pkg/indexmanagement/reconcile.go
- pkg/indexmanagement/reconcile_test.go
- pkg/indexmanagement/scripts.go
- pkg/indexmanagement/validations.go
- pkg/k8shandler/common.go
- pkg/k8shandler/common_test.go
- pkg/k8shandler/elasticsearch.go
- pkg/k8shandler/index_management.go
- pkg/k8shandler/index_management_test.go
- pkg/k8shandler/util.go
- pkg/logger/logger.go
- pkg/types/elasticsearch/types.go
- pkg/types/k8s/configmap.go
- pkg/utils/comparators/envvars.go
- pkg/utils/comparators/envvars_test.go
- pkg/utils/comparators/maps.go
- pkg/utils/comparators/resources.go
- pkg/utils/comparators/tolerations.go
- pkg/utils/utils.go
- test/helpers/runtime/client.go
This PR addes indexmanagment cronjobs to satisfy:
https://issues.redhat.com/browse/LOG-571
> LOG-571: Add Indexmanagement cronjobs

- manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
Fix skip range for ART
https://bugzilla.redhat.com/show_bug.cgi?id=1803147
> Bug 1803147: fix skip range for ART

- pkg/k8shandler/cluster.go
- pkg/k8shandler/elasticsearch.go
- pkg/k8shandler/elasticsearch_test.go
Addresses https://issues.redhat.com/browse/LOG-606
> Adding logic to add alias for old indices to match new data structure

- manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1804166
>  Bug 1804166: Update minKubeVersion for 4.4

- manifests/4.3/elasticsearch-operator.v4.3.0.clusterserviceversion.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1804169
> Bug 1804169: set minKube version for 4.3

- Dockerfile
fix the Dockerfile so that it properly structures the manifest
> fix manifest so it has proper structure

- Makefile
- hack/common
- hack/cr.yaml
- hack/deploy-example-secrets.sh
- hack/testing/test-001-operator-sdk-e2e.sh
- hack/testing/test-200-verify-es-metrics-access.sh
- hack/testing/utils
- manifests/05-deployment.yaml
- manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
- manifests/4.5/image-references
- pkg/k8shandler/common.go
- pkg/k8shandler/service.go
- test/e2e/elasticsearch_test.go
> LOG-620 Replace proxy

- pkg/k8shandler/common.go
- pkg/k8shandler/common_test.go
- pkg/k8shandler/configuration_tmpl.go
- pkg/k8shandler/confimaps_test.go
- test/helpers/envvars.go
- test/helpers/yaml.go
This PR
* utilizes the downward api to fix the ipv6 binding
Fixes:
* https://bugzilla.redhat.com/show_bug.cgi?id=1811867
* https://bugzilla.redhat.com/show_bug.cgi?id=1791231
> Bug 1811867: Fix binding to ipv6

- olm_deploy/scripts/catalog-deploy.sh
make it slightly easier to use the scripts to deploy EO w/o setting any explicit variables.
> default the eo operator registry image variable

- pkg/k8shandler/elasticsearch_helper.go
Added a type check guard for index replica count response from Elasticsearch
> Fix EO panic when response from elasticsearch is not as expected

- pkg/k8shandler/elasticsearch_helper.go
Forward the SA token in the request as part of the authentication header
> Forward SA token to ES for auth

- hack/test-e2e-olm.sh
- hack/testing-olm/utils
Block the indexmanagment test for @bparees olm changes
> exclude im-block-test

- hack/test-e2e-olm.sh
- pkg/k8shandler/configuration_tmpl.go
- pkg/k8shandler/confimaps_test.go
This PR re-introduces auto-create of indices with a 'write' suffix
https://bugzilla.redhat.com/show_bug.cgi?id=1809511
> Bug 1809511: block autocreation of indices with 'write' suffix

- Makefile
- pkg/controller/elasticsearch/controller.go
- pkg/controller/kibana/controller.go
- pkg/controller/proxyconfig/controller.go
- pkg/indexmanagement/expectations_test.go
- pkg/indexmanagement/reconcile_test.go
- pkg/k8shandler/cluster.go
- pkg/k8shandler/common.go
- pkg/k8shandler/common_test.go
- pkg/k8shandler/configmaps_test.go
- pkg/k8shandler/defaults.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/elasticsearch.go
- pkg/k8shandler/elasticsearch_helper.go
- pkg/k8shandler/elasticsearch_test.go
- pkg/k8shandler/index_management_test.go
- pkg/k8shandler/kibana/reconciler.go
- pkg/k8shandler/nodetypefactory.go
- pkg/k8shandler/statefulset.go
- pkg/k8shandler/util.go
- pkg/logger/logger.go
Changelist:
* Code cleanup:
*  Removed unused methods
*  Fixed error handlings for skipped errors
*  Fixed implicitly used fields
* Added `golang-ci-lint` as a prerequisite for `make build`
> Code cleanup. Make linter a mandatory target to run

- pkg/k8shandler/kibana/consolelink.go
- pkg/k8shandler/kibana/kibana_test.go
- pkg/k8shandler/kibana/reconciler.go
- pkg/k8shandler/kibana/route.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1803196
> Bug 1803196: Replace shared config map with console link CRs

- pkg/k8shandler/common.go
updating from `pods/metrics` to `pods/log`
> fixing auth sar for sg_role_admin

- pkg/indexmanagement/reconcile.go
- pkg/indexmanagement/reconcile_test.go
This PR renames the crons for index management to include the cluster name
> rename crons for index managment

- pkg/indexmanagement/reconcile.go
- pkg/indexmanagement/scripts.go
> cleaning up and optimizing delete cronjob

- hack/testing-olm/test-001-operator-sdk-e2e.sh
- hack/testing-olm/test-657-im-block-autocreate-for-write-suffix.sh
- hack/testing-olm/utils
This PR applies the same debug log extensions as openshift/cluster-logging-operator#474
> Enhance debug experience for E2E operator registry

- pkg/k8shandler/deployment.go
- pkg/k8shandler/statefulset.go
This ticket fixes these bugs: 
* https://bugzilla.redhat.com/show_bug.cgi?id=1824006
* https://bugzilla.redhat.com/show_bug.cgi?id=1825088
> Bug 1826781: Added ENV comparison for ES deployment and stateful set

- manifests/4.5/elasticsearches.crd.yaml
- pkg/constants/constants.go
- pkg/indexmanagement/reconcile.go
- pkg/k8shandler/common.go
- pkg/k8shandler/defaults.go
https://bugzilla.redhat.com/show_bug.cgi?id=1826451
> Bug 1826451: Make indexmanagment rely on packaged es image

- olm_deploy/operatorregistry/Dockerfile
Update dockerfile to get registry Binary from bin
> Update dockerfile to get registry Binary from bin

- hack/test-e2e.sh
- hack/testing/test-001-operator-sdk-e2e.sh
- pkg/k8shandler/deployment.go
- pkg/k8shandler/statefulset.go
- pkg/utils/comparators/envvars.go
- pkg/utils/comparators/envvars_test.go
- test/e2e/elasticsearch_test.go
- test/utils/utils.go
This PR resolves the following bug: https://bugzilla.redhat.com/show_bug.cgi?id=1824006
It is a port of this PR https://github.com/openshift/elasticsearch-operator/pull/316 to 4.4 release + fix for E2E test.
> Bug 1824006: Backported fix for ES ENV

- pkg/constants/constants.go
Renamed kibana CR instance that EO is watching for from **instance** to **kibana**
> Bug 1833142: Renamed kibana CR instance

- pkg/k8shandler/deployment.go
- pkg/k8shandler/deployment_test.go
This PR:
* fixes envvar updates to persist changes from the updated container
* adds a test to check
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1824006
> Bug 1824006: fix update of env vars

- pkg/k8shandler/deployment.go
- pkg/k8shandler/deployment_test.go
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1826781
pulled in test from https://github.com/openshift/elasticsearch-operator/pull/352
> Bug 1826781: Add test to support container checks

- manifests/4.5/image-references
This has been blocking EO builds.
> bug 1817592: downstream kibana name is logging-kibana6

- hack/testing-olm/test-200-verify-es-metrics-access.sh
- pkg/apis/logging/v1/elasticsearch_types.go
- pkg/k8shandler/defaults.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/statefulset.go
- pkg/utils/comparators/envvars.go
- pkg/utils/utils.go
- test/e2e-olm/elasticsearch_test.go
- test/e2e-olm/utils.go
Updating policies based on updated ES docs https://www.elastic.co/guide/en/elasticsearch/reference/6.8/rolling-upgrades.html
> Bug 1836452: Updating upgrade policy to allow yellow and set only primaries

- pkg/indexmanagement/scripts.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1835083
> Bug 1835083: Add missing mTLS credentials for indexmanagement jobs

- pkg/k8shandler/kibana/reconciler.go
- pkg/k8shandler/kibana/reconciler_test.go
The deployment will be marked as changed when the number of replicas is changed.
> Bug 1836866: Fixed deployment trigger when replicas changed

- pkg/elasticsearch/indices.go
> Bug 1837323: Fixed EO crash

- hack/cr.yaml
To fix : https://bugzilla.redhat.com/show_bug.cgi?id=1833268
> Bug 1833268: revert logs-* aliases to logs.*

- pkg/elasticsearch/client.go
- pkg/elasticsearch/cluster.go
- pkg/elasticsearch/cluster_test.go
- pkg/k8shandler/cluster.go
- pkg/k8shandler/common.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/nodetypefactory.go
- pkg/k8shandler/statefulset.go
- pkg/k8shandler/status.go
- pkg/types/elasticsearch/types.go
- pkg/utils/comparators/versions.go
- pkg/utils/comparators/versions_test.go
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1841832
> Bug 1841832: network policy to allow ES pod loopback and intercluster communication

- pkg/indexmanagement/scripts.go
Reverts openshift/elasticsearch-operator#372
> Revert "Bug 1835083: Add mTLS credentials to rollover IM script"

- pkg/indexmanagement/scripts.go
Reverts #360 
Complements #374 for the delete scripts
This reverts commit c02c8b69600cbe042df54bd884503cbdb60730dd.
> Revert "Bug 1835083: Add missing mTLS credentials for indexmanagement jobs

- pkg/controller/kibanasecret/controller.go
- pkg/controller/proxyconfig/controller.go
- pkg/controller/trustedcabundle/controller.go
- pkg/k8shandler/cr.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1842043
Needs backport: release-4.5
> Bug 1842043: Stop reconciliation on ES CR not present

- pkg/controller/kibana/controller.go
- pkg/k8shandler/kibana/reconciler.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1842865
> Bug 1842865: Fix Reconcile loop return values

- manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
- manifests/art.yaml
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1845539
Needs backport: release-4.5
> Bug 1845539: Update skipRange constraint to 4.4.0

- pkg/k8shandler/kibana/reconciler.go
- pkg/k8shandler/migrations/migrations.go
EO was not updating the annotation value for the secret hashes when they were different.
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1834576
> Bug 1834576: Fixing kibana not rolling out with secret update

- pkg/apis/logging/v1/elasticsearch_types.go
- pkg/k8shandler/cluster.go
- pkg/k8shandler/defaults.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/elasticsearch.go
- pkg/k8shandler/statefulset.go
- pkg/k8shandler/status.go
- pkg/utils/comparators/envvars.go
- pkg/utils/utils.go
Addresses:
* https://bugzilla.redhat.com/show_bug.cgi?id=1844302
* https://bugzilla.redhat.com/show_bug.cgi?id=1845993
Manual cherrypicks of:
* https://github.com/openshift/elasticsearch-operator/pull/388
* https://github.com/openshift/elasticsearch-operator/pull/365
* https://github.com/openshift/elasticsearch-operator/pull/355
* (partial) https://github.com/openshift/elasticsearch-operator/pull/386
> [release-4.4] Bug 1845993: Fix unnecessary restarts and harden rolling restarts

- pkg/k8shandler/kibana/kibana_test.go
- pkg/k8shandler/kibana/reconciler.go
- pkg/k8shandler/kibana/route.go
- test/e2e-olm/kibana_test.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1847450
**Needs backport:** release-4.5
cc @jhadvig
> Bug 1847450: Publish only one console link for Kibana

- hack/testing-olm-upgrade/resources/cr.yaml
- hack/testing-olm-upgrade/test-020-olm-upgrade-4.4-4.5.sh
- hack/testing-olm/assertions
- hack/testing-olm/utils
- pkg/k8shandler/deployment.go
- pkg/k8shandler/statefulset.go
Added E2E upgrade test for the Elasticseach operator. This test isn't part of the `test-olm`, because it will be running in a separate job in the CI.
> LOG-385: Added E2E ES upgrade test

- pkg/k8shandler/configmaps.go
- pkg/k8shandler/configmaps_test.go
- pkg/k8shandler/configuration_tmpl.go
> [release-4.4] Bug 1854472: k8shandler: disable system_call_filter check on non-amd64 architectures

- manifests/4.6/elasticsearches.crd.yaml
- olm_deploy/scripts/operator-install.sh
- pkg/apis/logging/v1/elasticsearch_types.go
- pkg/apis/logging/v1/zz_generated.deepcopy.go
- pkg/constants/constants.go
- pkg/k8shandler/common.go
- pkg/k8shandler/common_test.go
- pkg/k8shandler/defaults.go
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1856502
> Bug 1856502: Add ES-Proxy Resources to Elasticsearch CR

- pkg/k8shandler/configmaps.go
- pkg/k8shandler/configuration_tmpl.go
> [release-4.3] Bug 1855072: k8shandler: disable system_call_filter check on non-amd64 architectures

- manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
This reverts commit a79baf5930214bc167d8ddafeffa2e21fe2bc700, reversing changes made to f4404f2b109764da070443513b976a4f0efc7563.
> Bug 1852889: Revert "Merge pull request #428 from periklis/revert-minkubeversion-1-18-3"

- Makefile
- bundle/bundle.Dockerfile
- bundle/manifests/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
- bundle/manifests/elasticsearches.crd.yaml
- bundle/manifests/image-references
- bundle/manifests/kibanas.crd.yaml
- bundle/metadata/annotations.yaml
Generated using `make generate-bundle`
To address changes required as part of https://issues.redhat.com/browse/OLM-1810
> Updating EO to use operator bundle

- files/prometheus_alerts.yml
- pkg/k8shandler/prometheus_rule.go
add alert to alerts for low file descriptors and linear prediction high disk usage
This PR also adds update ability to the alerts reconciler. 
/cc @ewolinetz @periklis @lukas-vlcek
> Bug 1865364: alert for out of file descriptors

- pkg/k8shandler/deployment.go
- pkg/k8shandler/podtemplate.go
- pkg/k8shandler/podtemplate_test.go
- pkg/k8shandler/util.go
Manual partial cherrypick of: https://github.com/openshift/elasticsearch-operator/pull/400
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1861529
> [release-4.5] Bug 1861529: fixing rollout detection for deployments

- hack/testing-olm-upgrade/test-020-olm-upgrade-4.4-4.5.sh
Removed usage of associative arrays for upgrade test as they don't work properly for bash 4.2
> Bug 1874081: Fixed 4.4->4.5 upgrade test

- bundle.Dockerfile
Updating bundle labels per:
* https://docs.engineering.redhat.com/display/CFC/Migration
> updating bundle labels to be used for nightly

- pkg/k8shandler/cluster.go
This PR addresses an important corner case during cluster/operator upgrades when populating the operator with node deployment/statetfulset specs. During population the current routine deletes any nodes specs from the apiserver if they are not reflected by the elasticsearch CR. Although the `status.nodes` is updated correctly, this change is not persisted until a later point. However, a restart of the operator or cluster in between may leave some bits in `status.nodes` (e.g. Unschedulable condition) for an already deleted node deployment/statefulset. In turn any remaining `Unschedulable` conditions will bring the operator to halt because the unschedulable node is deleted.
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1873652
> Bug 1873652: Update cluster status after populating nodes

- pkg/indexmanagement/scripts.go
This PR is multiple backports for 4.5 to fix up deleting indices 
* https://github.com/openshift/elasticsearch-operator/pull/454
* https://github.com/openshift/elasticsearch-operator/pull/477
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1868675
> Bug 1868675: Delete indices in batches

- hack/testing-olm-upgrade/test-020-olm-upgrade-4.4-4.5.sh
* Fixed broken `log::info` call
> Fixed E2E 4.4 -> 4.5 upgrade test

- pkg/indexmanagement/scripts.go
This PR adds a connect timeout for index management jobs to keep the jobs from hanging
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1881709
> Bug 1881709: Add connect timeout for IM jobs

- pkg/k8shandler/status.go
- pkg/k8shandler/status_test.go
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1887357
Fixing passing nodes to have their status conditions updated, change was not appearing due to not correctly passing node to be updated.
The status not being updated prevented the operator from evaluating a node as unschedulable during its normal reconcile loop so it could not adjust the memory request|limit for nodes that had already been created.
> Bug 1887357: Correctly updating the elasticsearch node conditions 

- pkg/k8shandler/status.go
- pkg/k8shandler/status_test.go
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1880926
Manual cherry-pick of https://github.com/openshift/elasticsearch-operator/pull/531
Fixing passing nodes to have their status conditions updated, change was not appearing due to not correctly passing node to be updated.
The status not being updated prevented the operator from evaluating a node as unschedulable during its normal reconcile loop so it could not adjust the memory request|limit for nodes that had already been created.
> Bug 1880926: Correctly updating the elasticsearch node conditions

- pkg/utils/resources.go
- pkg/utils/utils_test.go
- add test cases
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1889573
- JIRA: https://issues.redhat.com/browse/OCPBUGSM-19482?filter=-1
> Bug 1889573: Fix nil map in updating kibana resource

- hack/testing-olm-upgrade/test-020-olm-upgrade-4.4-4.5.sh
This PR modifies the 4.4-4.5 ES upgrade test by verifying custom indices.
/cc @ewolinetz @jcantrill 
/assign @ewolinetz @jcantrill @alanconway
> Added custom index verification for ES upgrade test

- files/dashboards/logging-dashboard-elasticsearch.json
Updating Elasticsearch metrics dashboard. Improving some charts and updating the dashboard title.
> Bug 1892755: Update Elasticsearch dashboard

- .gitignore
- Makefile
This PR adds the missing unit test coverage report for this repository.
/assign @ewolinetz @jcantrill 
- JIRA: https://issues.redhat.com/browse/LOG-816
> Add coverage report for test-unit target

- manifests/4.5/elasticsearches.crd.yaml
- olm_deploy/scripts/operator-install.sh
- pkg/apis/logging/v1/elasticsearch_types.go
- pkg/apis/logging/v1/zz_generated.deepcopy.go
- pkg/constants/constants.go
- pkg/k8shandler/common.go
- pkg/k8shandler/common_test.go
- pkg/k8shandler/defaults.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/podtemplate.go
- pkg/k8shandler/podtemplate_test.go
- pkg/k8shandler/recovery.go
- pkg/k8shandler/statefulset.go
- pkg/k8shandler/util.go
- pkg/utils/resources.go
Cherry pick of changes for fixing bug 1856502
including the fix "Fixing rollout detection, settings being overwritten mid update, and function call ordering"
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1856502
> Bug 1894632: Add ES-Proxy Resources to Elasticsearch CR

- golangci.yaml
- pkg/elasticsearch/indices.go
- pkg/elasticsearch/templates.go
- pkg/indexmanagement/expectations_test.go
- pkg/indexmanagement/reconcile.go
- pkg/indexmanagement/validations_test.go
- pkg/k8shandler/cluster.go
- pkg/k8shandler/clusterrestart.go
- pkg/k8shandler/common.go
- pkg/k8shandler/common_test.go
- pkg/k8shandler/configmaps.go
- pkg/k8shandler/defaults.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/index_management_test.go
- pkg/k8shandler/kibana/defaults.go
- pkg/k8shandler/kibana/pod_test.go
- pkg/k8shandler/kibana/reconciler.go
- pkg/k8shandler/kibana/reconciler_test.go
- pkg/k8shandler/kibana/status.go
- pkg/k8shandler/migrations/kibana5to6.go
- pkg/k8shandler/nodetypefactory.go
- pkg/k8shandler/statefulset.go
- pkg/k8shandler/status.go
- pkg/utils/utils.go
- test/helpers/json.go
Fix lint errors from `make lint`
/cc @periklis 
> LOG-968: fix lint issues

- Makefile
- hack/testing-olm-upgrade/upgrade-common
Fixing the upgrade script to ensure that we are trying to deploy a prior version of the EO from operatorhub that is in the catalog
/cc @blockloop @periklis
> fixing up deploying latest version available to catalog

- pkg/indexmanagement/scripts.go
Handle invalid json input in the delete index script
/assign @jcantrill  
/cherry-pick 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1899905
> Bug 1899905: Handle invalid json in delete script

- hack/testing-olm-upgrade/test-020-olm-upgrade-4.4-4.5.sh
- hack/testing-olm/utils
Added debug output for old a new indices for the ES-4.4-4.5 upgrade test
/cc @periklis 
/assign @periklis @ewolinetz 
/cherry-pick 
- Bugzilla:
- Github issue:
- JIRA:
- Enhancement proposal:
> Added debug output for old and new indices for ES upgrade test

- docs/alerts.md
- files/prometheus_alerts.yml
- test/files/prometheus-unit-tests/test.yml
- Provide links in the alert message
- Descriptions about the alerts in the troubleshooting.md
- Github issue: https://issues.redhat.com/browse/LOG-453
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1913469
> BUG 1913469: LOG-453 Expose recommendations based on cluster health

- Dockerfile
- Dockerfile.centos.patch
- hack/common
- hack/testing-olm-upgrade/upgrade-common
- olm_deploy/operatorregistry/Dockerfile
- olm_deploy/scripts/catalog-deploy.sh
This PR updates the container registry per dev email regarding the decommissioning of the other registry
cc @ewolinetz
> Update container registry to registry.ci.openshift.org

- pkg/controller/kibana/controller.go
Manual cherry-pick #549 
/cc @ewolinetz @periklis 
/cherry-pick 4.5
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1926276
> [release-4.6] Bug 1926276: watch route deletion in kibana controller:

- olm_deploy/scripts/catalog-deploy.sh
GET THE LOGGING VERSION RIGHT!!!
> fix logging version to 5.1

- hack/prometheus-rules.yaml
This PR updates the Prometheus alerts to have the appropriate severity level.
/cc @periklis 
- JIRA: https://issues.redhat.com/browse/LOG-1097
> Changing severity level of prometheus alerts

- hack/testing-olm-upgrade/upgrade-common
This PR is a cherry-pick of #664 into master.
/cc @vimalk78 
- JIRA: https://issues.redhat.com/browse/LOG-1183
> Fix upgrade tests for release-5.x

- internal/indexmanagement/scripts.go
Note, do not link the bugzilla in the title. That is only relevant for the 4.6 branch cherrypick and will link it there.
During a load test it can happen where permissions are not correctly evaluated and a http 500 is returned when trying to get index aliases. It is observed to not be a constant issue and retry will usually be successful.
This PR adds retries into the cronjob curl commands for the case where this is an intermittent issue.
Due to how we store the responses with the retry we make them look like an array of json responses so that we can properly parse them out and evaluate what the last response was (because we either succeed eventually or we fail the whole time).
Also given delete and rollover were having issues with the same block of code I removed the delete pattern of …
> Adding safeguards to cronjob to be more resilient to es 500 responses

- internal/indexmanagement/scripts.go
Addresses issue seen in one of the must gathers for https://bugzilla.redhat.com/show_bug.cgi?id=1922943 where somehow Elasticsearch has a write-index that points to two different indices (this is not allowed under normal conditions -- e.g. you cannot mark a second index as the write-index while another one is currently the write-index).
Note: it is still undetermined if this is the reason for all the other issues seen on the bz mentioned above so for now it is not considered a fix for it. Looking to backport to 4.6 for stability reasons.
This will mark all but the latest write-index to not be the write-index and then return the single write-index.
/cc @periklis @blockloop @jcantrill 
/cherry-pick release-5.0
> Adding logic to remove any duplicate write index targets for an alias

- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- manifests/5.1/elasticsearch-operator.v5.1.0.clusterserviceversion.yaml
Resolves regression seen in https://bugzilla.redhat.com/show_bug.cgi?id=1939979 where we introduce a resource request/limit for the elasticsearch operator.
/cc @vimalk78 @jcantrill 
will require manual cherrypick to release-5.0
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1939979
> Removing resource request and limits from EO deployment definition

- Makefile
This PR renames linting task to 'lint'
https://issues.redhat.com/browse/LOG-1279
> LOG-1279: Rename linter task to lint

- Dockerfile
- olm_deploy/operatorregistry/Dockerfile
- olm_deploy/scripts/catalog-deploy.sh
- pkg/indexmanagement/scripts.go
Cherrypicking cronjob script fixes to better handle retries and incorrectly formatted responses.
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1925307
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1947781
> Bug 1925307: Cherypicking updates to index management scripts

- .gitignore
- Makefile
- internal/elasticsearch/client.go
- internal/elasticsearch/replicas.go
- internal/k8shandler/reconciler.go
- internal/k8shandler/statefulset.go
- internal/k8shandler/status.go
- internal/k8shandler/util.go
- internal/k8shandler/util_test.go
- main.go
- test/e2e-olm/elasticsearch_metric_test.go
- test/e2e-olm/utils.go
- test/utils/utils.go
Fixing up lint errors from `make lint` target to resolve CI errors
/cc @blockloop @jcantrill
> fixing up lint errors

- bundle/manifests/logging.openshift.io_elasticsearches_crd.yaml
- manifests/4.6/logging.openshift.io_elasticsearches_crd.yaml
- pkg/apis/logging/v1/elasticsearch_types.go
Manual cherrypick of: #686
Fix crd incompability during upgrading from 4.5 to 4.6
> Bug 1946772: fix es crd status incompatible when upgrading operator

- pkg/controller/add_controllers.go
- pkg/controller/secret/controller.go
- pkg/k8shandler/deployment.go
- pkg/k8shandler/nodetypefactory.go
- pkg/k8shandler/reconciler.go
- pkg/k8shandler/statefulset.go
Manual cherrypick of #667 and #695
/cc @periklis
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1923788
> Bug 1923788: Add secret reconciler to trigger restarts for secret changes

- internal/k8shandler/status.go
Corrects https://github.com/openshift/elasticsearch-operator/pull/685. In the previous PR, the PVC module was not being correctly grabbed for each node and thus caused the conditions to always appear. This correctly grabs the PVC and then updates the conditions appropriately and removed some redundancies in the code.
/cc @periklis 
- JIRA: https://issues.redhat.com/browse/LOG-920
> Log 920: Getting the PVC for each node

- docs/alerts.md
This PR
- Fixes the critical alert playbook commands after a discussion with QE
- JIRA: https://issues.redhat.com/browse/LOG-1098
> Critical alerts playbook fixes

- olm_deploy/scripts/operator-install.sh
This PR echos the subscription upon operator install. Trying to resolve 5.2 CI
cc @ewolinetz 
https://issues.redhat.com/browse/LOG-1342
> Display subscription that is being created

- internal/k8shandler/deployment.go
- internal/k8shandler/podtemplate.go
- internal/k8shandler/podtemplate_test.go
- internal/k8shandler/statefulset.go
- internal/k8shandler/status.go
"Cherry pick" from here https://github.com/openshift/elasticsearch-operator/pull/715
- JIRA: https://issues.redhat.com/browse/LOG-920
> LOG-920: Preventing upgrade when changes done to the storage

- internal/indexmanagement/reconcile.go
This PR ensures that the environment variable `POLICY_MAPPING` exists only once for delete/hot IndexManagement containers. This enables the k8s apiserver to internally migrate v1beta1/CronJob resources to v1/CronJob w/o issues.
- JIRA: https://issues.redhat.com/browse/LOG-1130
> LOG-1130: Fix duplicate container env var for policy mapping

- internal/k8shandler/certificates.go
Nit follow up for EO cert management opt-in
/cc @periklis
> tidying up validateCASecret

- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
- manifests/5.0/elasticsearch-operator.v5.0.0.clusterserviceversion.yaml
Update the operator to identify infrastructure features:
* disconnected
* proxy-aware
* https://issues.redhat.com/browse/LOG-1459
* https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs
> LOG-1459: Annotate with infrastructure features

- internal/k8shandler/deployment.go
- internal/k8shandler/statefulset.go
- test/e2e-olm/elasticsearch_test.go
This PR is a manual cherry-pick of: #740.
- JIRA: https://issues.redhat.com/browse/LOG-1537
> [release-5.0] LOG-1537: Fix full cluster cert redeploy with non-data nodes

- internal/indexmanagement/reconcile.go
- internal/indexmanagement/reconcile_test.go
- internal/indexmanagement/scripts.go
This is a backport of #746 for `release-5.0`
- JIRA: https://issues.redhat.com/browse/LOG-1461
> LOG-1461: Fix cronjob exit code handler for combined delete and rollover exec

- internal/indexmanagement/reconcile.go
- internal/indexmanagement/reconcile_test.go
- internal/indexmanagement/scripts.go
This is a backport of #744 for `release-5.1`
- JIRA: https://issues.redhat.com/browse/LOG-1460
> LOG-1460: Fix cronjob exit code handler for combined delete and rollover exec

- OWNERS
Added Periklis and Igor as approvers
> release-5.0: Updated OWNERS file

- OWNERS
Added Periklis and Igor as approvers
> release-4.6: Updated OWNERS file

- apis/logging/v1/elasticsearch_types.go
- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- internal/constants/constants.go
- internal/indexmanagement/reconcile.go
- internal/indexmanagement/scripts.go
- manifests/5.2/elasticsearch-operator.v5.2.0.clusterserviceversion.yaml
This PR:
- updates indexManagement curl commands to use es-python client.
- updates the referenced image for indexManagement to use curator image.
/cc @periklis 
- JIRA: https://issues.redhat.com/browse/LOG-927
> LOG-927: Update indexManagement script to use es-python client

- bundle.Dockerfile
- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- internal/constants/constants.go
- internal/kibana/defaults.go
- olm_deploy/operatorregistry/registry-deployment.yaml
- olm_deploy/scripts/catalog-deploy.sh
- olm_deploy/scripts/registry-init.sh
This manual backport of #786.
To address: https://issues.redhat.com/browse/LOG-1697
> [release-5.2] Use pinned operand image versions from quay.io

- files/dashboards/logging-dashboard-elasticsearch.json
This PR:
- Updates the dashboard file to show correct namespace count.
/cc @QiaolingTang 
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-1722
> LOG-1722: Update dashboard file to show correct namespace count

- internal/elasticsearch/serviceaccount.go
- internal/kibana/serviceaccount.go
- internal/manifests/serviceaccount/serviceaccount.go
This PR is porting #793 to master.
> Fix mutating serviceaccount annotations on updates

- olm_deploy/operatorregistry/registry-deployment.yaml
- olm_deploy/scripts/catalog-deploy.sh
- olm_deploy/scripts/registry-init.sh
This PR is a manual backport of #792.
To address: https://issues.redhat.com/browse/LOG-1698
> [release-5.2] Fix olm deploy env naming for curator operand image

- Dockerfile
- Dockerfile.dev
- Dockerfile.in
This change set ensures that the Dockerfiles are in sync with midstream
To address: https://issues.redhat.com/browse/LOG-1750
> Sync dockerfile with midstream

- olm_deploy/scripts/operator-install.sh
This PR fixes broken local deployment for 5.2
/cc @periklis 
> [release-5.2] Fixed package channel version

- Makefile
- olm_deploy/scripts/operator-install.sh
This PR fixes broken local deployment (`make deploy`)
/cc @periklis 
> Fixed broken local deployment

- files/prometheus_alerts.yml
- test/files/prometheus-unit-tests/test.yml
This PR is manual backport of #808 
> [release-5.1] LOG-1858: OpenShift Alerting Rules Style-Guide Compliance

- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- bundle/manifests/logging.openshift.io_elasticsearches.yaml
- config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
Added arm64 as supported arch in CSV
/cc 
/assign 
- JIRA: https://issues.redhat.com/browse/LOG-2085
> LOG-2085: Add arm64 as supported arch in CSV

- internal/manifests/persistentvolume/persistentvolumeclaim.go
This PR causes the operator to check for the existence of the PVC before attempting to create it. ResourceQuota errors are returned as a 403, so we cannot fire the create method first before checking without creating a PVC during every reconcile period.
/cc @sasagarw 
- JIRA: https://issues.redhat.com/browse/LOG-2118
> Log 2118: Checking for PVC Existence Before Create

- internal/elasticsearch/certificates.go
Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>
/cc 
/cherry-pick 
- Bugzilla:
- Github issue:
- JIRA:  https://issues.redhat.com/browse/LOG-1923
- Enhancement proposal:
> Align distinguished name (DN) of the certificate generated by EO with CLO

- internal/indexmanagement/reconcile.go
This PR:
- Fixes cronjob keeps recreating after enabling delete by query.
- fmt fixes.
/cc @shwetaap 
- JIRA: https://issues.redhat.com/browse/LOG-2161
> LOG-2161: Fix cronjob deletion when delete by query is enabled

- internal/indexmanagement/scripts.go
This PR is extension of #841 
/cc @btaani
- JIRA: https://issues.redhat.com/browse/LOG-2216
> LOG-2216: Update index management script

- internal/k8shandler/util.go
- internal/k8shandler/util_test.go
- internal/utils/comparators/tolerations.go
Manual cherry-pick of https://github.com/openshift/elasticsearch-operator/pull/850
- JIRA: https://issues.redhat.com/browse/LOG-2309
> [release-5.1] Log 2309: Special Tolerations Block Operator Update

- controllers/logging/kibana_controller.go
Adding the CA secret to the list of secrets for the Kibana Controller to watch. Without this, the controller will not reconcile if the CA secret is recreated and Kibana will not be able to communicate with Elasticsearch. With the PR, the controller will restart the pod with the appropriate certificates.
/cc @sasagarw 
- JIRA: https://issues.redhat.com/browse/LOG-2342
> Log 2342: Kibana certificates update when ca secret is recreated

- internal/indexmanagement/scripts.go
In the recent feature where indices can be deleted by disk percentage, the write-index was deleted when its size exceeded the maximum allowed size. This PR prevents the write-index from being deleted
/cc @sasagarw 
- Depending on PR(s): #848 
- JIRA: [LOG2444](https://issues.redhat.com/browse/LOG-2444)
> Fix deleting write index

- internal/elasticsearch/rbac.go
- internal/manifests/rbac/clusterrole.go
- internal/manifests/rbac/clusterrolebinding.go
This is a manual application of #867.
/cc @btaani 
- JIRA: https://issues.redhat.com/browse/LOG-2437
> Log 2437: Changing prometheus-k8s permissions scope

- internal/elasticsearch/rbac.go
- internal/manifests/rbac/clusterrole.go
- internal/manifests/rbac/clusterrolebinding.go
This is a manual application of #867.
/cc @btaani 
- JIRA: https://issues.redhat.com/browse/LOG-2481
> Log 2481: Changing prometheus-k8s permissions scope

- internal/elasticsearch/rbac.go
- internal/manifests/rbac/clusterrole.go
- internal/manifests/rbac/clusterrolebinding.go
This is a manual application of #867.
/cc @btaani 
- JIRA: https://issues.redhat.com/browse/LOG-2480
> Log 2480: Changing prometheus-k8s permissions scope

- README.md
Signed-off-by: Benedikt Bongartz <bongartz@klimlive.de>
Fix link in Readme
> fix link to operator capability level

- internal/kibana/reconciler.go
This fixes an issue with the current logic for determining the oauth-proxy image used by looking at the ImageStream data available on the cluster. The current implementation only uses the internal registry image name, which causes issues when the internal registry is not available in the cluster.
The new code will fall back to the source image name, should the internal registry not be available.
**Note:** I have not tested this change on a cluster yet, as I am still figuring out how to get the operator installed without an internal registry. The Makefile does not seem to support this case yet.
/cc @periklis 
/cherry-pick release-5.4
- JIRA: https://issues.redhat.com/browse/LOG-2679
> LOG-2679: Fallback to source image when internal registry is unavailable

- internal/indexmanagement/scripts.go
This PR fixes the accidental deletion of write-indices in case multiple index aliases belong to the same policy (e.g., `app-*` and `app-test-*`).
- Depending on PR(s): #848 and #865 
- JIRA: [LOG-2444](https://issues.redhat.com/browse/LOG-2444)
> Fix write-index deletion in delete by percentage

- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- internal/constants/constants.go
- internal/elasticsearch/common.go
- internal/kibana/reconciler.go
This PR adds the images under the `relatedImages` section. 
/cc @shwetaap 
- JIRA: https://issues.redhat.com/browse/LOG-2751
> LOG-2751: Using related images naming scheme

- OWNERS
> [release-4.6] Update OWNERS

- internal/kibana/kibana_test.go
- internal/kibana/reconciler.go
This is a backport of #904 for release 5.4.
- Github issue: #904 
- JIRA: [LOG-2791](https://issues.redhat.com/browse/LOG-2791)
> [release-5.4] LOG-2791: Fix Elasticsearch operator not respecting referencePolicy when selecting oauth-proxy image

- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
- olm_deploy/operatorregistry/registry-deployment.yaml
Signed-off-by: Shweta Padubidri <spadubid@redhat.com>
Making the ES operator PSA compliant
/cc @Red-GV 
- JIRA: [LOG-2736](https://issues.redhat.com//browse/LOG-2736)
> Making the ES operator PSA compliant

- bundle/manifests/logging.openshift.io_elasticsearches.yaml
- bundle/manifests/logging.openshift.io_kibanas.yaml
- config/crd/bases/logging.openshift.io_elasticsearches.yaml
- config/crd/bases/logging.openshift.io_kibanas.yaml
This PR updates the bundle configuration and completes the changes by #920 
> Update bundle configuration

- test/e2e/elasticsearch_metric_test.go
Provides ServiceAccountToken Secrets for the E2E Metrics tests' ServiceAccounts. Since k8s 1.24 and OCP 4.11 ServiceAccounts do not provide the tokens per default and the creator needs to create separate Secret themselves.
> Fix e2e metrics tests for OCP 4.11

- bundle/metadata/properties.yaml
This PR adds the properties file to the bundle. The properties file is the location where dependencies and specific properties (like the maximum supported OpenShift version) can be defined.
> Adding properties file

- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- internal/constants/constants.go
- internal/elasticsearch/common.go
- internal/kibana/reconciler.go
> Using related images naming scheme

- apis/logging/v1/groupversion_info.go
- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/logging/kibana_controller.go
- internal/constants/constants.go
- internal/elasticsearch/common.go
- internal/kibana/kibana_test.go
- internal/kibana/reconciler.go
- internal/kibana/reconciler_test.go
- internal/utils/comparators/envvars.go
- internal/utils/utils.go
cherry-pick of #954 
/cc @periklis 
- JIRA: [LOG-3306](https://issues.redhat.com/browse/LOG-3306)
> [release-5.4] LOG-3306: Fix kibana oauth cookie expiration issue

- olm_deploy/operatorregistry/registry-deployment.yaml
This PR fixes the seccompprofile to remove warning and blockers for deployment of the catalog source to unblock clo mater tests
> fix seccompProfile of registry bundle

- Dockerfile
- Dockerfile.dev
- Dockerfile.in
- dev-meta.yaml
- go.mod
- origin-meta.yaml
/cc 
/assign 
/cherry-pick 
- Bugzilla:
- Github issue:
- JIRA:
- Enhancement proposal:
> Bump go to 1.20 and RHEL to 9

- internal/indexmanagement/scripts.go
Skip index rollover when the write-index is empty. This is to avoid creating lots of empty indices on the long run
- JIRA: [LOG-4452](https://issues.redhat.com/browse/LOG-4452)
> Skip rollover when index is empty

- internal/indexmanagement/reconcile.go
Add a fallback routine to initialize the default Index Management mapping name alias to the first index, e.g. `app` to `app-000001`. 
> LOG-4683: Init always the mapping name alias for the first index

- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
Provide infrastructure annotations to pass downstream build pipeline.
> [release-5.6] LOG-4859: Add infrastructure annotations

- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
Provide infrastructure annotations to pass downstream build pipeline.
> [release-5.7] LOG-4859: Add infrastructure annotations

- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
Add "Observability" to the list of categories in the csv so that it shows in OperatorHub
- https://issues.redhat.com/browse/LOG-4691
> LOG-4691: Add to observability category in operatorhub

- internal/indexmanagement/scripts.go
Prevent returning and error when the alias doesn't exist or when there are no indices in alias.
- JIRA: [LOG-4949](https://issues.redhat.com/browse/LOG-4949)
> LOG-4949: Handle not existing index properly in management jobs

- bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml
- config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
Add the following support statement on the top of the CSV description regarding 4.16:
/cc @jcantrill
> LOG-5911: Add partial support statement for 4.16

- go.mod
Follow-up to #1018 to fix the build.
> NO-JIRA: Fix toolchain directive in Go module
