openshift/elasticsearch-operator

Makefile
This PR removes build info from compile to resolve downstream issue
=> remove build info from ldflags

pkg/k8shandler/desirednodestate.go
This variable is no longer significant and setting up the prometheus endpoint
=> remove PROMETHEUS_USER var

cmd/elasticsearch-operator/main.go, pkg/k8shandler/cluster.go, pkg/k8shandler/configmaps.go, pkg/k8shandler/deployment.go, pkg/k8shandler/desirednodestate.go, pkg/k8shandler/services.go, pkg/stub/handler.go, pkg/utils/utils.go
Enable log level and format selection and change verbosity of existing log statements.
I'm assuming that the log level in production
will be 'warn' and for development 'debug' or 'info'
=> Enable log level and format selection

Makefile, deploy/examples/onenode-emptydir-es.yaml, deploy/examples/onenode-hostmounted-es.yaml, deploy/examples/onenode-pvc-es.yaml, deploy/openshift/elasticsearch-template.yaml, deploy/operator.yaml, hack/common, hack/deploy-setup.sh, hack/deploy.sh, manifests/05-deployment.yaml, pkg/stub/handler.go
This allows better integration with cluster-logging-operator -
from cluster-logging-operator can do things like `make deploy-setup`
and it will call `make -C ${ES_OP_DIR} deploy-setup` to also
setup elasticsearch.
This also removes the `quay.io/` prefix from images to make
it easier to use the locally built images.
=> more cleanup - better integration with cluster-logging-operator

hack/test-e2e.sh, manifests/02-role.yaml, pkg/k8shandler/status.go
The operator needs to use the `oc` command and so needs a kubeconfig file.  The kubeconfig file can be constructed at startup in a manner similar to https://github.com/openshift/origin-aggregated-logging/blob/v1.2.0/deployment/run.sh#L12
- construct the `$HOME/.kubeconfig` similar to the above - overwrite if it already exists
- `SetEnv("KUBECONFIG", "$HOME/.kubeconfig")`
Then subsequent calls to `oc` will automatically use this.
=> construct kubeconfig from sa secret and downward api

pkg/k8shandler/services.go, pkg/k8shandler/util.go
... to call readiness script.
This fixes a regression previously resolved in our ansible installation.
Noticed this while dev testing:
```
$ oc exec elasticsearch-clientdatamaster-0-1-76578dc89c-99hvr -- check
Thu Dec  6 22:07:56 UTC 2018
epoch      timestamp cluster       status node.total node.data shards pri relo init unassign pending_tasks max_task_wait_time active_shards_percent
1544134076 22:07:56  elasticsearch yellow          1         1      9   9    0    0        6             0                  -                 60.0%
ip           heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
10.128.0.126           13          99  23    0.17    0.56     1.04 mdi       *      elasticsearch-clientdatamaster-0-1
health status index                  uuid …
```
=> Updating services to publish not ready and updating readiness probe

Makefile, README.md, hack/common, hack/deploy-image.sh, hack/deploy.sh
Make it so that setting Makefile vars exports the key ones
as env. vars for the scripts.
Fix use of `REMOTE_REGISTRY=true` so that it works in older
i.e. minishift environments as well as newer `openshift-install`
environments
=> fix unexported env. vars. and remote registry integration

pkg/apis/elasticsearch/v1alpha1/types.go, pkg/k8shandler/cluster.go, pkg/k8shandler/deployment.go, pkg/k8shandler/status.go, pkg/k8shandler/util.go, pkg/utils/exec_util.go, pkg/utils/utils.go
Support Rolling Restart on Image Change
In order to support minor releases of OpenShift logging
users will need to run rolling restart of the cluster.
This restart can be triggered bu updating
`ElasticsearchNodeSpec.Image`.
A prerequisite is that the cluster health is in green state.
This rolling restart will upgrade the cluster in a node-by-node fashion,
always one node at a time.
The operators waits for shard reallocation after every node upgrade,
thus a full upgrade procedure can take significat time to finish.
Synced flush is used to lower the total time that it takes
for the whole cluster to upgrade and reballance shards.
If the cluster restart procedure fails, a human intervention
is needed to bring the cluster back to operation.
=> Log250 rolling restart

pkg/apis/elasticsearch/v1alpha1/types.go
this will update our json formatting for storage from:
```
storage:
storageClass:
storageClassName: "gp2"
size: "20G"
```
to:
```
storage:
storageClassName: "gp2"
size: "20G"
```
Internally this does not affect code
=> Updating storageclass to be inline for json formatting

pkg/k8shandler/service_monitor.go
Corrects the path for the CACert file for the ServiceMonitor to partially resolve https://bugzilla.redhat.com/show_bug.cgi?id=1660778
=> fix 166078. Correct the CACert file for servicemonitor

pkg/k8shandler/cluster.go, pkg/k8shandler/deployment.go, pkg/k8shandler/desirednodestate.go, pkg/k8shandler/nodetypefactory.go, pkg/k8shandler/statefulset.go
Change of the number of environmental variables or labels
makes the operator crash. This patche adds checks for lengths
of the respective arrays.
https://bugzilla.redhat.com/show_bug.cgi?id=1662105
=> Guard against array index ouf of bound error

Makefile, hack/common, hack/deploy-image.sh, hack/deploy-setup.sh, hack/image-stream-build-config-template.yaml, hack/undeploy.sh
If USE_IMAGE_STREAM=true, setup a buildconfig and an
image stream in the remote repo, and build the operator image
there from the github source.  This may save a lot of time
as opposed to building the image locally and pushing the image
into the remote registry.
Also allow deploying without first building the image.  This
assumes something like a CI environment where the previous
CI stage builds the images needed to deploy and test.
=> support buildconfigs and no image build deployments

hack/undeploy.sh, manifests/02-role.yaml, manifests/03-role-bindings.yaml, manifests/05-deployment.yaml
Part of work for ES per namespace hackfest item for Jaeger integration
Note that this is not installed via OLM in the same way so that means a normal OLM installation will not give the Elasticsearch Operator full cluster watch authz
=> Updating es manifest to allow it to watch all namespaces

cmd/elasticsearch-operator/main.go
sdk.ExposeMetricsPort() leaks Service and is deprecated
in future version of the sdk.
For now, we won't be exposing metrics of the operator, but we plan
to do that later. This change has no impact on exposing metrics
of the elasticsearch cluster as a whole.
=> Don't use the sdk for exposing operator's metrics

files/prometheus_alerts.yml, hack/cr.yaml, hack/deploy-setup.sh, hack/prometheus-rules.yaml, hack/test-e2e.sh, manifests/02-role.yaml, manifests/05-deployment.yaml, pkg/k8shandler/deployment.go, pkg/k8shandler/desirednodestate.go, pkg/k8shandler/rbac.go, pkg/k8shandler/service_monitor.go, pkg/k8shandler/services.go, pkg/k8shandler/statefulset.go, pkg/k8shandler/util.go, pkg/stub/handler.go, pkg/utils/utils.go
Prometheus server can't access ES metrics, because ES uses certs
signed by a self-signed CA, which isn't recognized.
Instead a proxy is used, which presents certs signed by a CA
which can be accessed through serving-certs-ca-bundle
=> Secure metrics endpoint with oauth-proxy

pkg/k8shandler/rbac.go
fixes jira.coreos.com/browse/LOG-353
=> bug LOG-353 - oauth proxy doesnt start when deployed into different namespace

hack/test-e2e.sh
The tests should be run in a different namespace that `openshift-logging` to ensure that the operator can be deployed in a different namespace e.g. for Jaeger. 
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
=> Use test namespace for e2e tests

pkg/apis/elasticsearch/v1alpha1/types.go, pkg/k8shandler/cluster.go, pkg/k8shandler/common.go, pkg/k8shandler/configmaps.go, pkg/k8shandler/deployment.go, pkg/k8shandler/elasticsearch.go, pkg/k8shandler/statefulset.go, pkg/k8shandler/status.go, pkg/k8shandler/util.go, test/e2e/elasticsearch_test.go, test/e2e/main_test.go, test/utils/utils.go
Adding conditions for invalid settings so they aren't just displayed in the operator logs to address part of https://jira.coreos.com/browse/LOG-339
```
conditions:
- lastTransitionTime: 2019-03-06T23:33:00Z
message: Invalid master nodes count. Please ensure there are no more than 3 total
nodes with master roles
reason: Invalid Settings
status: "True"
type: InvalidMasters
- lastTransitionTime: 2019-03-06T23:28:37Z
status: "False"
type: InvalidData
- lastTransitionTime: 2019-03-06T23:28:38Z
status: "False"
type: InvalidRedundancy
- lastTransitionTime: 2019-03-06T23:30:35Z
message: Config Map is different
reason: ConfigChange
status: "True"
type: UpdatingSettings
- lastTransitionTime: 2019-03-06T23:28:52Z
status: "False"
type: ScalingUp
- lastTransitionTime: 2019-03-06T23:28:52Z
status: …
```
=> Improved status conditions

pkg/k8shandler/persistentvolumeclaims.go, pkg/k8shandler/statefulset.go
Removing unnecessary output when creating PVCs in the elasticsearch operator
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1691230
=> Bug 1691230 - Removing unnecessary output regarding pvc

Makefile, pkg/k8shandler/common.go, pkg/k8shandler/common_test.go
This is instead of just using default for missing value as is currently done.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1686173
=> Bug 1686173 - Use request or limit if other is not provided for resource requirements

pkg/k8shandler/deployment.go, pkg/k8shandler/statefulset.go
We were only checking differences for the `elasticsearch` container, this expands to check all containers in the `elasticsearch` pod.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1691256
=> Bug 1691256 - updating to check proxy changes

pkg/apis/elasticsearch/v1/types.go, pkg/apis/elasticsearch/v1/zz_generated.deepcopy.go, pkg/k8shandler/common.go, pkg/k8shandler/deployment.go, pkg/k8shandler/statefulset.go, pkg/k8shandler/util.go, pkg/k8shandler/util_test.go
If node selectors have changed for Elasticsearch nodes then we should recognize this change and perform a rolling restart with the changes.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1694097
=> Bug 1694097 - Check if nodeselectors have changed

pkg/k8shandler/service.go, pkg/k8shandler/service_monitor.go
There was a mismatch between labels and port name in metrics svc and service monitor.
=> Fix 1662273 - cant find es metrics

pkg/k8shandler/deployment.go, pkg/k8shandler/statefulset.go
We were unnecessarily falling through into logic that was reserved just for brand new nodes which was interfering with correctly evaluating if changes were required.
Ref: 
https://bugzilla.redhat.com/show_bug.cgi?id=1686173
https://bugzilla.redhat.com/show_bug.cgi?id=1691256
https://bugzilla.redhat.com/show_bug.cgi?id=1694511
=> Bug 1686173 - Correctly evaluate case where node previously existed

pkg/k8shandler/deployment.go, pkg/k8shandler/elasticsearch.go
Print out better message that informs users about how many data
shards in to be flushed.
Make sure restart steps follow official documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/rolling-upgrades.html
=> Bug 1703546: Waiting for synced flush

controller-manifests/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml
This env var is required be made available with the latest SDK, CI didn't catch this because we are deploying from artifacts in `manifests` instead of `controller-manifests` like we do for clo.
=> fixing required deployment env var in manifest

pkg/k8shandler/common.go, pkg/k8shandler/common_test.go
To address elasticsearch not being scheduled to nodes where fluentd may have left buffer files causing disk-pressure, allow elasticsearch to be scheduled on nodes where that taint has been applied so it can be available for fluentd to attempt to clear its buffer files.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1707465
=> Bug 1707465: Adding disk-pressure toleration for elasticsearch

Dockerfile, Dockerfile.rhel7
while imagebuilder allowed this, docker+buildah do not seem to recognize the WORKDIR as a context for the `COPY --from` so it fails.
=> use absolute paths for COPY commands

Makefile, hack/deploy-setup.sh, hack/deploy.sh
Some minor fixes to allow oal logging CI to use
`make deploy`.  Use `IMAGE_OVERRIDE` to specify the exact
image to use.
=> allow logging CI to use make deploy

Makefile, README.md
This is to stick to same naming conventions as in Cluster Logging Operator Makefile.
See [openshift/cluster-logging-operator/Makefile](https://github.com/openshift/cluster-logging-operator/blob/62fe437dabf602ca6a3cea7b8f3119e4c08672ec/Makefile#L65).
=> Rename go-run target to run

Gopkg.lock, pkg/k8shandler/cluster.go, pkg/k8shandler/deployment.go, pkg/k8shandler/nodetypefactory.go, pkg/k8shandler/statefulset.go, pkg/k8shandler/util.go, pkg/k8shandler/util_test.go, vendor/github.com/go-openapi/spec/items.go, vendor/github.com/go-openapi/spec/schema.go, vendor/github.com/go-openapi/spec/swagger.go
If a node has been removed from `spec.nodes` we want to no longer manage it and delete it accordingly.
NOTE: currently, when removing a node that has been established already, the operator will flag that a previously used UUID is no longer available and will mark this as an invalid config. You will also need to remove it from status.nodes as well.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1707875
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1711044
=> Bug 1707875 - Remove nodes that arent in CR

manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml, manifests/elasticsearch-operator.package.yaml
This PR fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1718731 by reverting #151
=> Bug 1718731:  elasticsearch operator fails to install due to missing specDescriptor

manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml, manifests/art.yaml, manifests/elasticsearch-operator.package.yaml
This PR bumps CRV to 4.1.2 and adds art.yml file for future automation
=> bug 1717627. bump crv to 4.1.2

pkg/k8shandler/common.go, pkg/k8shandler/common_test.go
Previously we were setting the CPU limit to match the CPU request if the request was provided but the limit was not. This removes the logic to set the CPU limit for ES nodes unless it is explicitly defined.
=> Bug 1725148: Updating to not set CPU limit unless it is explicitly set

manifests/4.1/elasticsearch-operator.v4.1.0.clusterserviceversion.yaml, manifests/art.yaml, manifests/elasticsearch-operator.package.yaml
aligning w/ similar changes in master: https://github.com/openshift/elasticsearch-operator/pull/167
patch manager: there is no master BZ associated w/ this change because this is cleaning up issues that were specific to the 4.1 resource files.
=> bug 1724833: clean up 4.1 channel manifests

pkg/k8shandler/common.go, pkg/k8shandler/common_test.go, pkg/k8shandler/defaults.go
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1725249
Cherry pick of:
* https://github.com/openshift/elasticsearch-operator/pull/170
* https://github.com/openshift/elasticsearch-operator/pull/160
Combination of:
* https://github.com/openshift/elasticsearch-operator/pull/172 
* https://github.com/openshift/elasticsearch-operator/pull/163
=> Bug 1725249: Updating to not set CPU limit unless it is explicitly set

pkg/k8shandler/cluster.go, pkg/k8shandler/deployment.go, pkg/k8shandler/nodetypefactory.go, pkg/k8shandler/statefulset.go, pkg/k8shandler/util.go, pkg/k8shandler/util_test.go
Cherry pick of #144
If a node has been removed from spec.nodes we want to no longer manage it and delete it accordingly.
Replaces https://github.com/openshift/elasticsearch-operator/pull/149
NOTE: currently, when removing a node that has been established already, the operator will flag that a previously used UUID is no longer available and will mark this as an invalid config. You will also need to remove it from status.nodes as well.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1707875
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1711044
=> [release-4.1] Bug 1711044: Remove nodes that arent in CR

Makefile, pkg/k8shandler/elasticsearch.go
gosec does static code analysis and checks for common security issues in
golang codebases.
This PR introduces the tool, and sets it up as a test target in the Makefile.
This also makes the creation of the folder with certificates/keys more
restrictive. This was one of the warnings found by gosec.
=> Introduce gosec for security checks

Makefile, pkg/k8shandler/common_test.go, pkg/k8shandler/deployment.go, pkg/k8shandler/deployment_test.go
This fixes https://bugzilla.redhat.com/show_bug.cgi?id=1741350 by:
Only update the cpu/memory resources if they are greater then zero
blocked by https://github.com/openshift/elasticsearch-operator/pull/181
=> Bug 1741350: Set resource limits if they are greater then 0

hack/test-e2e.sh, pkg/apis/logging/v1/elasticsearch_types.go, pkg/k8shandler/cluster.go, pkg/k8shandler/deployment.go, pkg/k8shandler/nodetypefactory.go, pkg/k8shandler/statefulset.go, pkg/k8shandler/status.go, test/e2e/elasticsearch_test.go, test/utils/utils.go
As part of doing a redeploy due to certs being updated we need to do a full cluster restart otherwise nodes aren't able to rejoin the cluster due to cert mismatching.
=> Bug 1666167: Do a full cluster restart in case of cert redeploy

pkg/k8shandler/deployment.go, pkg/k8shandler/nodetypefactory.go, pkg/k8shandler/persistentvolumeclaims.go, pkg/k8shandler/statefulset.go
Manual cherry-pick of https://github.com/openshift/elasticsearch-operator/pull/186
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=1751320
=> Bug 1751320: Recreate nodes that have been deleted during upgrade

manifests/elasticsearch-operator.package.yaml
Need to update the package for 4.3. This is causing the oal ci failure
https://github.com/openshift/origin-aggregated-logging/pull/1765
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_origin-aggregated-logging/1765/pull-ci-openshift-origin-aggregated-logging-master-full-integ-aws/1497/build-log.txt
```
+++ curl -sOLJ https://raw.githubusercontent.com/openshift/elasticsearch-operator/master/manifests/elasticsearch-operator.package.yaml
...
https://github.com/openshift/origin-aggregated-logging/blob/master/hack/vendor/olm-test-script/e2e-olm.sh#L99
CURRENT_CSV=$(sed -nr 's,.*currentCSV: (.*),\1,p' $MANIFEST_DIR/*package.yaml)
```
so the version is in the package.yaml as well as elsewhere.
This will also need a similar change in the clo
=> update package for 4.3

pkg/k8shandler/elasticsearch_helper.go, pkg/k8shandler/rbac.go
Port of https://github.com/openshift/elasticsearch-operator/pull/193 to 4.3
https://bugzilla.redhat.com/show_bug.cgi?id=1765803
https://issues.jboss.org/browse/OSSM-100
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
=> Bug 1765803: Add subject per ES instance to es-proxy cluster role binding

pkg/k8shandler/deployment.go, pkg/k8shandler/statefulset.go
When the EO restarts it may go through and unnecessarily restart its managed clusters because it no longer has the secret hash stored for each node.
With this PR as long as the node is not in a state where it is currently scheduled to or is in the process of being restarted (denoted in the `.status` fields) we evaluate our hash when we check the state of each node.
=> Bug 1753568: Dont restart cluster just because EO restarted

pkg/k8shandler/elasticsearch_helper.go, pkg/k8shandler/rbac.go, test/e2e/elasticsearch_test.go
Port of https://github.com/openshift/elasticsearch-operator/pull/193 for 4.2
https://bugzilla.redhat.com/show_bug.cgi?id=1765808
https://issues.jboss.org/browse/OSSM-100
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
=> Bug 1765808: Add subject per ES instance to es-proxy cluster role binding

pkg/k8shandler/configuration_tmpl.go
remove elasticsearch 5 and openshift elasticsearch plugin specific
settings from elasticsearch.yml
Note - KibanaIndexMode is now unused - will leave it in for now
in case we want to use it in the future
=> support for es6 configmap

hack/cert_generation.sh, pkg/k8shandler/common.go
Make ES config ipv6 compatible to resolve: 
* [Bug 1791231](https://bugzilla.redhat.com/show_bug.cgi?id=1791231)
* [Bug 1791349](https://bugzilla.redhat.com/show_bug.cgi?id=1791349)
=> Bug 1791231: Make addresses ipv6 compatible

README.md, hack/cr.yaml, hack/test-e2e.sh, manifests/05-deployment.yaml, manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml, manifests/4.4/image-references, pkg/k8shandler/defaults.go, pkg/logger/logger.go, test/e2e/elasticsearch_test.go
This PR updates the operator to expect ESv6 and relies on images provided by:
* https://github.com/openshift/origin-aggregated-logging/pull/1817
=> Update operator to expect ESv6

Makefile, hack/build-image.sh, hack/cert_generation.sh, hack/deploy-image.sh, hack/deploy-setup.sh, hack/deploy.sh, hack/test-e2e.sh, hack/undeploy.sh
This PR disables default `set -x` for the EO deploy scripts and replaces it with the configuration env var `DEBUG`
=> Reduce deploy-example verbosity

pkg/k8shandler/common.go
(cherry picked from commit 07b717e7ad932c345e159c658ebde572f7fdf8d3)
https://bugzilla.redhat.com/show_bug.cgi?id=1794801
=> Bug 1794801: [IPv6] Application should service on Address [::]:port 

manifests/4.3/elasticsearch-operator.v4.3.0.clusterserviceversion.yaml
Fix an issue where the elasticsearch-operator couldn't be upgraded because it doesn't match the update_list defined in art.yaml nor configured in correct range.
4.3 fix https://github.com/openshift/elasticsearch-operator/pull/238
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1803145
=> Bug 1803145: Fix incorrect olm.skipRange in 4.3 CSV

hack/cr.yaml
OpenDistro security plugin parses role index patterns wrongly if it contains `.`, so using `-` instead.
Updated `logs.infra` to `logs-infra`
=>     Updated `logs.infra` to `logs-infra`

pkg/k8shandler/defaults.go
This PR reverts logs to the console in order to avert filling up disk with stray logs that are not properly rotated
=> revert ES logs to console

pkg/k8shandler/common.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1808053
=> Bug 1808053: Define default master url for fabric8io k8s client

manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
Adds a `"kubernetes.io/os": "linux"` node selector for the ClusterLoggingOperator deployment
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1808986
=> Bug 1808986: Adding nodeSelector to operator deployment

.gitignore, hack/test-e2e.sh, hack/testing/test-200-verify-es-metrics-access.sh, hack/testing/test-657-im-block-autocreate-for-write-suffix.sh, hack/testing/utils, pkg/k8shandler/configuration_tmpl.go
Block auto index creation for indices that end in `-write` to avoid a race condition between fluent writing logs and EO setting up index management
cc @QiaolingTang @ewolinetz 
https://bugzilla.redhat.com/show_bug.cgi?id=1809511
=> Bug 1809511: block creation of indices with the write suffix for index management

hack/test-e2e.sh, pkg/k8shandler/common.go, pkg/k8shandler/common_test.go, pkg/k8shandler/service.go
This PR extends the proxy container arguments to address the mandatory configuration for exposing metrics from a separate TLS listener using the injected PKI. To address: openshift/elasticsearch-proxy#25
=> Provide proxy configuration for metrics TLS listener

olm_deploy/scripts/registry-init.sh
these checks weren't doing anything since we set the env vars explicitly on the operator-registry catalog deployment, and we don't set image_format.
=> remove unused variable check paths

pkg/apis/logging/v1/elasticsearch_types.go
The CLO operator will soon generate CRDs from Go code, which uses Go comments
to fill in the CRD validation `description` fields. Add text and re-organized
comments to give better descriptions.
Signed-off-by: Alan Conway <aconway@redhat.com>
=> Re-organize comments to give better CRD `description` fields.

Makefile
Generating k8s API code referencing the golang std library needs a reference to GOROOT (See https://github.com/operator-framework/operator-sdk/issues/1545).
=> Fix missing GOROOT for CRD/API generation

hack/cr.yaml, pkg/k8shandler/common.go, pkg/k8shandler/common_test.go, pkg/k8shandler/configmaps.go, pkg/k8shandler/configmaps_test.go, pkg/k8shandler/defaults.go, pkg/k8shandler/deployment.go, pkg/k8shandler/statefulset.go, pkg/k8shandler/util.go, pkg/k8shandler/util_test.go, pkg/logger/logger.go, test/e2e-olm/elasticsearch_test.go
This PR adds the ability to configure the loglevel via an annotation so that we can get better log info while running tests.  It separates setting the loglevel of the security plugin from the rest of the server
=> Add annotation to configure loglevel

pkg/k8shandler/kibana/rbac.go, pkg/k8shandler/kibana/reconciler.go, pkg/k8shandler/kibana/route.go, pkg/k8shandler/kibana/serviceaccount.go, pkg/k8shandler/kibana/trustedcabundle.go
Looks like these were missed before...
ES currently:
```
ownerReferences:
- apiVersion: logging.openshift.io/v1
controller: true
kind: Elasticsearch
name: elasticsearch
uid: 6596d4f9-b8b8-4fee-b618-62ebca47f41e
```
Kibana currently:
```
ownerReferences:
- apiVersion: logging.openshift.io/v1
controller: true
kind: ClusterLogging
name: instance
uid: 017c1f4d-91dd-4a64-88ee-d65d880f34ad
```
Kibana with this change:
```
ownerReferences:
- apiVersion: logging.openshift.io/v1
controller: true
kind: Kibana
name: instance
uid: c321920e-7127-4574-9378-901fbb79d3aa
```
=> Fixing kibana owner refs

pkg/indexmanagement/scripts.go, pkg/k8shandler/common.go, pkg/k8shandler/common_test.go, pkg/k8shandler/rbac.go, pkg/types/k8s/configmap.go, pkg/types/k8s/rbac.go
This PR fixes IndexManagement crons to:
* utilize SA token
* Create role to a virtual resource for indexmanagent
* Configure proxy to evaluate role
cc @ewolinetz 
depends on https://github.com/openshift/origin-aggregated-logging/pull/1863
=> Add virtual role for indexmanagement cronjobs

Makefile
This PR removes any helper downloads on build to satisfy ART build process requirements and to prevent errors as seen here: openshift/cluster-logging-operator#436
=> Omit helper tool downloads for ART build process

manifests/4.4/elasticsearch-operator.v4.4.0.clusterserviceversion.yaml
Manual cherry-pick of https://github.com/openshift/elasticsearch-operator/pull/254
Adds a `"kubernetes.io/os": "linux"` node selector for the ClusterLoggingOperator deployment
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1812920
=> Bug 1812920: Adding nodeSelector to operator deployment

pkg/indexmanagement/reconcile.go
Minor tuning based on k8s docs:
Looking to adjust the amount of pods that are left behind, currently we see something like:
```
ocp-index-mgm-delete-app-1585950300-9rz25       0/1     Error     0          30m
ocp-index-mgm-delete-app-1585951200-7c9cx       0/1     Error     0          14m
ocp-index-mgm-delete-audit-1585950300-d9mct     0/1     Error     0          30m
ocp-index-mgm-delete-audit-1585951200-vsbq7     0/1     Error     0          14m
ocp-index-mgm-delete-infra-1585950300-gbkdw     0/1     Error     0          30m
ocp-index-mgm-delete-infra-1585951200-sz4lf     0/1     Error     0          14m
ocp-index-mgm-rollover-app-1585950300-dbzwm     0/1     Error     0          30m
ocp-index-mgm-rollover-app-1585951200-fpxlr     0/1     Error     0          14m …
```
=> Adjusting IM cj specs for namespace noise

olm_deploy/scripts/registry-init.sh
This PR addresses an issue on running E2E olm-based tests locally against a devcluster where the operator is already present on the nodes but a newer image was pushed by the development workflow.
This issue is not present on CI, because `IMAGE_FORMAT` (e.g. `egistry.svc.ci.openshift.org/ci-op-3cfm5kx8/stable:${component}`) ensures a stable unique name whether local development usually points to `your-registry-of-choice/openshift/origin-elasticsearch-operator:latest`. (cc @bparees)
=> Overwrite pull policy for local olm based E2E tests

pkg/constants/constants.go, pkg/controller/kibanasecret/controller.go, pkg/controller/trustedcabundle/controller.go, pkg/k8shandler/kibana/reconciler.go, pkg/k8shandler/kibana/reconciler_test.go
Changeset:
* TrustedCABundle controller isn't tied to `openshift-logging` namespace
* Kibana's ES path is now generated from the Kibana CR namespace
* Minor code fixes
=> Kibana isn't tied to openshift-logging namespace anymore

pkg/k8shandler/kibana/reconciler.go, pkg/k8shandler/kibana/reconciler_test.go
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1823606
Upstream fix for https://github.com/openshift/cluster-logging-operator/pull/480
=> Bug 1823606: Updating kibana update to also check proxy container env

manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
This PR adds missing permissions to allow the operator to set the owner reference to the metrics service resource.
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1827063
=> Bug 1827063: Grant perm to set owner ref to metrics Service resource

pkg/k8shandler/cluster.go, pkg/k8shandler/status.go
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=1827690
When an ES node is unable to be ready due to `ImagePullBackOff` we weren't allowing it to be fixed outside of a normal cluster restart (which requires the cluster to be in a certain condition which it would never reach).
This functionality is similar to the condition that the pod is unschedulable
=> Bug 1827690: Adding ImagePullBackOff condition to unschedulableNodes

hack/common
This PR removes a leftover to old testing scripts remove by #321 
cc @bparees
=> Fix leftover reference to hack/testing/utils

hack/build-image.sh, hack/common, hack/deploy-image.sh
This PR fixes the 4.4 `make deploy` target for our dev experience to depend on podman in light of our switch to rely on buildah
=> fix make deploy on 4.4

pkg/k8shandler/deployment.go, pkg/k8shandler/elasticsearch/elasticsearch_suite_test.go, pkg/k8shandler/elasticsearch/resources_test.go, pkg/k8shandler/elasticsearch/update.go, pkg/k8shandler/elasticsearch/update_test.go, pkg/k8shandler/statefulset.go, test/utils/utils.go
This PR:
* Adds comparison of an ES node's container args to determine if a change is needed
* Refactors deployment/stateful set into a common function
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1809498
=> Bug 1809498: Compare container args to determine update of node

pkg/k8shandler/cluster.go
This PR fixes changes from LOG-606 lost during merge or rebase 
Adding back in from bad merge.  Originally part of LOG-606
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1809498
=> Bug 1809498: Adding logic to add alias for old indices to match new data structure

pkg/controller/proxyconfig/controller.go, pkg/controller/trustedcabundle/controller.go, pkg/k8shandler/kibana/configmap.go, pkg/k8shandler/kibana/kibana_test.go, pkg/k8shandler/kibana/reconciler.go, pkg/k8shandler/kibana/trustedcabundle.go
This PR addresses several issues on reconciliation of the trusted CA-Bundle config map as well the hash annotation on the Kibana deployment.
To address:
- https://bugzilla.redhat.com/show_bug.cgi?id=1834311
- https://bugzilla.redhat.com/show_bug.cgi?id=1833273
Needs backport to: release-4.4
=> Bug 1834311: Fix trusted ca bundle and hash reconciliation

hack/deploy-example-secrets.sh, hack/test-e2e-olm.sh, hack/testing-olm/test-200-verify-es-metrics-access.sh, pkg/k8shandler/common.go, pkg/k8shandler/common_test.go, pkg/k8shandler/service.go
This PR adds the missing elasticsearch-proxy container port for the elasticsearch-metrics service. In addition it re-enables the `verify-es-metrics` E2E test.
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1832125
=> Bug 1832125: Expose es-metrics svc target port in proxy container

manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml, pkg/k8shandler/common.go, pkg/k8shandler/deployment.go, pkg/k8shandler/statefulset.go
This will allow the Elasticsearch Operator to prevent ingress traffic to the ES cluster on port 9200 from anywhere other than the Elasticsearch Operator pod itself.
This should assist in the upgrade process as we will be able to halt logs flowing in.
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1833145
=> Bug 1833145: Set network policy when doing upgrades to prevent connections

pkg/constants/constants.go, pkg/controller/kibana/controller.go, pkg/controller/kibanasecret/controller.go, pkg/controller/proxyconfig/controller.go, pkg/controller/trustedcabundle/controller.go, pkg/elasticsearch/client.go, pkg/elasticsearch/cluster.go, pkg/elasticsearch/cluster_test.go, pkg/elasticsearch/indices.go, pkg/elasticsearch/indices_test.go, pkg/elasticsearch/templates_test.go, pkg/k8shandler/cr.go, pkg/k8shandler/index_management_test.go, pkg/k8shandler/kibana/kibana_test.go, pkg/k8shandler/kibana/kibanarequest.go, pkg/k8shandler/kibana/reconciler.go, pkg/k8shandler/migrations/kibana5to6.go, pkg/k8shandler/migrations/kibana5to6_test.go, pkg/k8shandler/migrations/migrations.go, pkg/k8shandler/migrations/migrations_suite_test.go, pkg/k8shandler/migrations/migrations_test.go, pkg/types/elasticsearch/types.go, pkg/utils/utils.go, test/e2e-olm/utils.go, test/helpers/elasticsearch.go
This PR addresses the need to reindex the index during updating to kibana 6. Based on the official guide for elasticsearch installation w/o xpack:
https://www.elastic.co/guide/en/kibana/6.0/migrating-6.0-index.html
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1835903
Depends on: #356 ~openshift/origin-aggregated-logging#1900~
=> Bug 1835903: Reindex kibana index for kibana6

pkg/k8shandler/cluster.go, pkg/k8shandler/status.go
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=1840909
=> Bug 1840909: Updating cert restarts to also adhere to primaries instead of none

pkg/k8shandler/common.go, pkg/k8shandler/common_test.go
This PR:
* configures the elasticsearch proxy to define admin and default roles
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1837867
blocked by:
* https://github.com/openshift/elasticsearch-proxy/pull/39
* https://github.com/openshift/origin-aggregated-logging/pull/1902
=> Bug 1837867: configure default and admin roles for proxy

pkg/indexmanagement/scripts.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1842445
=> Bug 1842445: Drop xtrace to ensure token not visible in logs

pkg/indexmanagement/scripts.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1835083
Needs backport: release-4.5
=> Bug 1835083: Add mTLS credentials to rollover IM script

pkg/controller/proxyconfig/controller.go, pkg/k8shandler/cluster.go, pkg/k8shandler/cr.go, pkg/k8shandler/deployment.go, pkg/k8shandler/kibana/reconciler.go, pkg/k8shandler/statefulset.go
Addresses inconsistencies seen with networkpolicy like in https://bugzilla.redhat.com/show_bug.cgi?id=1841832
=> Bug 1841832: Removing calls to enforce and relax networkpolicy

pkg/k8shandler/deployment.go, pkg/k8shandler/deployment_test.go, pkg/k8shandler/elasticsearch_suite_test.go, pkg/k8shandler/kibana/k8shandler_suite_test.go, pkg/k8shandler/statefulset.go
This PR updates ports to desired to address the upgrade scenario where we modified exposed ports and clients are no longer able to communicate to the ES cluster
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1835083
=> Bug 1835083: Update ports if they differ from the desired

pkg/controller/proxyconfig/controller.go, pkg/elasticsearch/client.go, pkg/elasticsearch/cluster.go, pkg/elasticsearch/cluster_test.go, pkg/k8shandler/cluster.go, pkg/k8shandler/common.go, pkg/k8shandler/cr.go, pkg/k8shandler/deployment.go, pkg/k8shandler/kibana/reconciler.go, pkg/k8shandler/nodetypefactory.go, pkg/k8shandler/statefulset.go, pkg/k8shandler/status.go, pkg/types/elasticsearch/types.go, pkg/utils/comparators/versions.go, pkg/utils/comparators/versions_test.go
Manual cherrypick of:
* https://github.com/openshift/elasticsearch-operator/pull/367
* https://github.com/openshift/elasticsearch-operator/pull/383
367 was opened to address missing port definitions and namespace label selectors on the networkpolicy as well as performing a full cluster restart when upgrading from ES5x to ES6x.
383 removes the use of the network policy due to it working inconsistently, the fact that we do a full cluster restart and assign `primaries` for shard allocation should mitigate any risk that introducing a networkpolicy was going to address.
=> [release-4.5] Bug 1843715: Perform a full cluster restart when upgrading ES maj versions

pkg/indexmanagement/scripts.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1842445
Needs backport: release-4.5
=> Bug 1842445: Drop curl verbosity in index management scripts

olm_deploy/operatorregistry/Dockerfile
This PR addresses a newly incorporated change in the operator registry image that needs a temporary directory to back the bundles database before migrating. (See https://github.com/operator-framework/operator-registry/pull/332)
**Depends on:** openshift/cluster-logging-operator#563
**Needs backport:** release-4.5
=> Bug 1847413: Fix E2E olm registry migration

manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml, manifests/art.yaml
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1845539
**Needs backport:** release-4.5
=> Bug 1845539: Update olm.skipRange constraint to 4.4.0-0

pkg/k8shandler/configmaps.go, pkg/k8shandler/configuration_tmpl.go, pkg/k8shandler/confimaps_test.go
This bootstrap check requires architecture-specific supporting code in ElasticSearch, which upstream has outright refused to accept.
Fixing here instead of in logging-elasticsearch based on feedback in https://github.com/openshift/origin-aggregated-logging/pull/1927
=> Bug 1848696: disable system_call_filter check on non-amd64 architectures

Makefile, hack/testing-olm/test-200-verify-es-metrics-access.sh, hack/testing-olm/test-657-im-block-autocreate-for-write-suffix.sh, pkg/elasticsearch/client.go, pkg/k8shandler/kibana/reconciler.go, test/e2e-olm/elasticsearch_test.go, test/e2e-olm/kibana_test.go, test/e2e-olm/main_test.go, test/e2e-olm/utils.go, test/utils/utils.go
This PR addresses the fragility of our E2E tests for elasticsearch cluster reconciliation. The present state consists of multiple E2E test cases glued together using the same elasticsearch cluster. This approach yields breaks test isolation. The new state isolates each test case by:
* Providing cleanup after each test case
* Using independent CR instances (e.g. `elasticsearch-$UUID`) and cluster deployments (e.g. `elasticsearch-$UUID-{cd,cdm}-$nodeUUID-...`)
* Usinge independent CR secrets and unique certificates per test case
* Continues to run test cases sequentially to keep resource usage on CI to the old levels. The preference is one cluster at a time thus one test case at a time.
/cc @ewolinetz
=> Refactor E2E tests to separate test cases

manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
In order for the elasticsearch-operator to be correctly filtered in
the OperatorHub for s390x and ppc64le we need to add the correct arch
label as supported.
=> Bug 1850546: Add support label for s390x & ppc64le

olm_deploy/scripts/operator-install.sh
This addresses the issue that we need to use labels instead of annotations to allow metrics to be collected for a particular namespace.
=> updating to label ns instead of annotate

manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
This PR addresses a bump of minKubeVersion to 1.18.3 because elasticsearch-operator is using client-go 1.18.x-only APIs and complies with 1.18.x upstream deprecation removals (See #291)
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1852889
=> Bug 1852889: Bump minKubeVersion to 1.18.3

go.mod, test/e2e-olm/elasticsearch_test.go, test/utils/utils.go
This PR is a follow-up for #412 to address missing asserts that the pod specifications are update to the desired state on a rolling restart scenario for a multi-node elasticsearch cluster (See [discussion](https://github.com/openshift/elasticsearch-operator/pull/412#discussion_r450258050) here).
Depends on #400 
/cc @ewolinetz
=> Check pod spec for E2E elasticsearch cluster restart test cases

manifests/4.5/elasticsearch-operator.v4.5.0.clusterserviceversion.yaml
In order for the elasticsearch-operator to be correctly filtered in
the OperatorHub for s390x and ppc64le we need to add the correct arch
label as supported.
(cherry picked from commit 1a0cb8ffc8ab1a1865cd9ac463ea5d85e64427bf)
=> [release-4.5] Bug 1855312: Add support label for s390x & ppc64le

pkg/k8shandler/configmaps.go, pkg/k8shandler/configuration_tmpl.go, pkg/k8shandler/confimaps_test.go
=> [release-4.5] Bug 1854262: k8shandler: disable system_call_filter check on non-amd64 architectures

manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
This PR reverts commit aa421b4defc37caf35c10054b4c00e9549ea77e7 and in extend downgrades the `minKubeVersion` to `1.17.0`, because apiserver on CI is still on `v1.17.0-alpha.0.7867+649a587b0a0f5d-dirty`
=> Revert "Bug 1852889: Bump minKubeVersion to 1.18.3"

pkg/k8shandler/configmaps_test.go, pkg/k8shandler/configuration_tmpl.go
Index level metrics contain high cardinality labels (index names and segment IDs). This can cause issues tto Prometheus and consume a lot of Prometheus storage.
=> Bug 1858249: Disable indices level metrics in Prometheus exporter output

pkg/constants/constants.go, pkg/indexmanagement/converters.go, pkg/indexmanagement/converters_test.go
The IndexManagement is configured to rollover index if any of existing conditions is met. We have
conditions on index size, number of document and age. Currently the condition on number of documents
in the index was calculated assuming the size of individual document (a single log) is up to 1M.
This is oversized for most of the real cases and is causing the index to be rolled over when 120.000
documents are stored in the index (given 3/1 prim/replicas sharding). This can easily lead to 10 new
infra indices per hour (about 300mb size each) on an "idle" OCP cluster.
We are going to update the condition to assume average size of individual log is a lot less (~1K). But in general this is not about assumed size of individual log message but about increasing the number of documents stored in …
=> Bug 1857826: Assume average log message is 1K

pkg/k8shandler/configuration_tmpl.go, pkg/k8shandler/confimaps_test.go
Index level metrics contain high cardinality labels (index names and segment IDs). This can cause issues tto Prometheus and consume a lot of Prometheus storage.
manual cherry-pick of https://github.com/openshift/elasticsearch-operator/pull/427
=> [release-4.5] Bug 1859991: Disable indices level metrics in Prometheus exporter output

pkg/constants/constants.go, pkg/indexmanagement/converters.go, pkg/indexmanagement/converters_test.go
The IndexManagement is configured to rollover index if any of existing conditions is met. We have
conditions on index size, number of document and age. Currently the condition on number of documents
in the index was calculated assuming the size of individual document (a single log) is up to 1M.
This is oversized for most of the real cases and is causing the index to be rolled over when 120.000
documents are stored in the index (given 3/1 prim/replicas sharding). This can easily lead to 10 new
infra indices per hour (about 300mb size each) on an "idle" OCP cluster.
We update the condition to assume average size of individual log is a lot less (~1K). But in general this is not about assumed size of individual log message but about increasing the number of documents stored in index before …
=> [release-4.5] Bug 1860135: Assume average log message is 1K

Dockerfile, files/dashboards/logging-dashboard-elasticsearch.json, pkg/k8shandler/configmaps.go, pkg/k8shandler/dashboards.go, pkg/k8shandler/reconciler.go, pkg/k8shandler/status.go
This adds an elasticsearch dashboard to the console. I will update with a screenshot after some metrics have been gathered. 
/cc @lukas-vlcek @ewolinetz
=> LOG-700 add elasticsearch metrics dashboard

hack/deploy-example-secrets.sh, hack/kibana-cr.yaml, hack/testing-olm/test-001-operator-sdk-e2e.sh, hack/testing-olm/test-657-im-block-autocreate-for-write-suffix.sh, pkg/k8shandler/cluster.go, pkg/k8shandler/clusterrestart.go, pkg/k8shandler/deployment.go, pkg/k8shandler/elasticsearch.go, pkg/k8shandler/statefulset.go, pkg/k8shandler/status.go, pkg/k8shandler/util.go, pkg/k8shandler/util_test.go, test/e2e-olm/elasticsearch_test.go, test/utils/utils.go
This PR attempts to optimize the flow within `k8shandler/cluster.go` to be easier to read and be more reactive to changes required for the cluster.
Addresses https://issues.redhat.com/browse/LOG-791
=> Optimizing cluster.go workflow

go.mod, vendor/modules.txt
This PR addresses a small miss from #439 upgrading to Golang 1.14.
=> Fix go version declaration in go.mod

pkg/k8shandler/deployment.go, pkg/k8shandler/podtemplate.go, pkg/k8shandler/podtemplate_test.go, pkg/k8shandler/statefulset.go, pkg/k8shandler/util.go, pkg/utils/resources.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1856502
While detecting if our proxy resources have been correctly applied and present in the running pod we would see the `desired` changes get lost and match the `current` values. So we would get a false positive that changes have been correctly rolled out.
=> Bug 1856502: Fixing rollout of nodes when proxy resources are updated

pkg/k8shandler/util.go, pkg/k8shandler/util_test.go
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1868282
Previously we did validation that the `RedundancyPolicy` was validated against the number of data nodes, given that for `SingleRedundance` we had at least 2 data nodes. This was mistakenly removed as part of relying on CRD validation to ensure that policies matched a given enum.
This change adds it back in and also validates that we have at least 2 data nodes for any redundancy policy other than `ZeroRedundancy`.
=> Bug 1868282: adding redundancy validation based on number of data nodes

pkg/indexmanagement/scripts.go
This PR:
* add error checking when looking for the "write" alias
* batches deletes to avoid cases where ES doesn't like a really long url (e.g. too long frame)
This PR may not resolve the issue as it looks like there is possibly a security exception related to an expired token.  It will add some additional info to the logs to hopefully expose more for debugging
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1866019
=> Bug 1866019: Delete indices in batches

files/prometheus_alerts.yml
Flood Stage Watermark has been introduced in ES 6.x
All watermark threshold values are now pulled from ES configuration
and not hardcoded (thus they should reflect custom settings).
=> Add Flood Stage Watermark alert

files/prometheus_alerts.yml, pkg/k8shandler/prometheus_rule_test.go
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1869117
Alerts file was incorrectly formatted which caused failures when trying to parse the yaml file.
Added unit tests to catch this in the future.
Nice to have (currently investigating if possible with our unit tests) would be to also validate the PromQL
/cc @blockloop
=> Bug 1869117: fixing alerts formatting, add unit test to validate

manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1868280
Adds a missing permission for `service/finalizers` that caused the following error upon operator start up:
```
{"level":"info","ts":1597218564.9376895,"logger":"cmd","msg":"Could not create ServiceMonitor object","error":"servicemonitors.monitoring.coreos.com \"elasticsearch-operator-metrics\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
```
=> Bug 1868280: fixing csv permissions to allow creation of servicemonitor object

test/e2e-olm/elasticsearch_test.go, test/e2e-olm/utils.go
I believe some of our CI tests are failing because of limited resources.
I believe we have our resource requests set too high for these tests.
=> require less resources for e2e testing

Makefile, hack/testing-olm/test-001-operator-sdk-e2e.sh
Removing the `-v` flag from `go test` prevents Go from printing any of the 
t.Log messages unless the test fails.
=> make tests less verbose

pkg/indexmanagement/scripts.go
This PR further updates https://bugzilla.redhat.com/show_bug.cgi?id=1868675 by removing the space when crafting the url for deleting indices
=> Bug 1866019: Remove space from joining deleting indices call

bundle/manifests/logging.openshift.io_elasticsearches_crd.yaml, bundle/manifests/logging.openshift.io_kibanas_crd.yaml, hack/generate-crd.sh, manifests/4.6/logging.openshift.io_elasticsearches_crd.yaml, manifests/4.6/logging.openshift.io_kibanas_crd.yaml
This PR addresses a recommended upgrade of the `apiVersion` of cluster-logging-operator managed CRDs from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`. Former is deprecated in upcoming k8s release 1.19 and very likely removed in 1.20. In extent addressing this upgrade sooner than later frees the operator upgrade procedure from limbo to enable installation of version `N` on an OCP cluster version `N-1`, where the cluster version has dropped the deprecated versions.
**Depends on:** #442
This PR needs to get rebased after #442 is merged. Please consider only the last **two** commits!
=> Bug 1871737: Upgrade CRD apiVersion apiextensions.k8s.io from v1beta1 to v1

files/prometheus_alerts.yml
https://bugzilla.redhat.com/show_bug.cgi?id=1873013
The configured alerts try to join metrics without any matching labels so
the result is always "No Data." Because the watermark metrics do not
contain the "cluster" and "node" labels they cannot be used in the alert
message.
/cc @lukas-vlcek
=> Bug 1873013: fix disk watermark alerts

pkg/k8shandler/kibana/reconciler.go
This PR reverts partially #467 to remove the cookie refresh, because the oauth server does not support refresh tokens.
=> Bug 1867461: Remove cookie-refresh flag for kibana-proxy

pkg/k8shandler/kibana/consolelink.go, pkg/k8shandler/kibana/kibana_test.go
This PR addresses a minor issue in placing the Logging inside the application launcher on a dedicated general purpose section named "Observability" instead of "Monitoring".
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1875478
/cc @ewolinetz @blockloop @sichvoge
=> Bug 1875478: Rename console link section Monitoring to Observability

pkg/k8shandler/common.go
This PR remove the obsolete annotation `tuned.openshift.io/elasticsearch` since release 4.4. The old tuning profile for setting `vm.max_map_count: 262144` is now already part of the defaults and thus obsolete.
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1876236
=> Bug 1876236: Drop unused tuned.openshift.io/elasticsearch annotation

manifests/4.6/logging.openshift.io_kibanas_crd.yaml, pkg/apis/logging/v1/kibana_types.go, pkg/controller/kibana/controller.go, pkg/k8shandler/kibana/kibanarequest.go, pkg/k8shandler/kibana/reconciler.go
This PR addresses two issues with updating the kibana status:
1. Usage of the kibana status subresource in go code while missing activation in the CRD.
2. Reconciling the status field along the pod lifecycle and not once during creation time.
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1849564
=> Bug 1849564: Update kibana status for ready pods

pkg/indexmanagement/scripts.go
This PR:
* Adds error checking to exit delete script if response is not a dict
* Walks the response tree checking for expected keys
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1866019
=> Bug 1866019: Add more error checking to delete script

pkg/k8shandler/cluster.go, pkg/k8shandler/common.go, pkg/k8shandler/index_management.go, pkg/k8shandler/migrations/kibana5to6.go, pkg/k8shandler/persistentvolumeclaims.go, pkg/k8shandler/podtemplate.go, pkg/k8shandler/podtemplate_test.go, pkg/k8shandler/recovery.go, pkg/k8shandler/status.go, pkg/k8shandler/util.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1868300
This addresses cases where there is or was an existing cluster created (deployments, pods, pvcs, etc) who's cluster name is the same as the CR name, however the new elasticsearch CR is missing UUIDs.
As part of the recovery/adoption process, it will be required that the PVCs to be picked back up have the label `logging-cluster: <name-of-the-cr>`. It will also be validated against the name of the cluster that the PVC name is based on.
Recovery/adoption will be triggered upon the processing of a CR that is missing UUIDs. It will only try to recover UUIDs for nodes that do not already have UUIDs defined.
Further documentation will need to be developed and publish as part of how to recover data that from another PVC. This PR does …
=> Bug 1868300: Updating EO to adopt existing uuids from pvcs or deployment objects if nil in CR

docs/pvc-recovery.md
Follow up for https://github.com/openshift/elasticsearch-operator/pull/471
This will eventually need to make it into the official OCP docs to document how a customer can recover old PVC data from a past cluster if they were impacted by https://bugzilla.redhat.com/show_bug.cgi?id=1868300
=> Documenting how to reindex from remote to recover old PVC data

pkg/k8shandler/kibana/reconciler.go
Fixed application panic when dereferencing annotations for kibana deployment.
=> Bug 1880845: Fixed panic when dereferencing nil pointer for annotations

pkg/indexmanagement/scripts.go
This PR resolves a python KeyError when evaluating which indices is the "write" one
https://bugzilla.redhat.com/show_bug.cgi?id=1882525
=> Bug 1882525: Resolve KeyError when determining indices to delete

pkg/k8shandler/cluster.go, pkg/k8shandler/common.go, pkg/k8shandler/migrations/kibana5to6.go, pkg/k8shandler/persistentvolumeclaims.go, pkg/k8shandler/podtemplate.go, pkg/k8shandler/podtemplate_test.go, pkg/k8shandler/recovery.go, pkg/k8shandler/util.go
To address https://bugzilla.redhat.com/show_bug.cgi?id=1881957
Manual cherry-pick of https://github.com/openshift/elasticsearch-operator/pull/471
This addresses cases where there is or was an existing cluster created (deployments, pods, pvcs, etc) who's cluster name is the same as the CR name, however the new elasticsearch CR is missing UUIDs.
As part of the recovery/adoption process, it will be required that the PVCs to be picked back up have the label logging-cluster: <name-of-the-cr>. It will also be validated against the name of the cluster that the PVC name is based on.
Recovery/adoption will be triggered upon the processing of a CR that is missing UUIDs. It will only try to recover UUIDs for nodes that do not already have UUIDs defined.
Further documentation will need to be …
=> [release-4.5] Bug 1881957: updating EO to adopt an existing cluster if cr nodes uuid is nil

pkg/k8shandler/cluster.go
This PR addresses a manual backport of #481 for `release-4.5` because of [merge conflicts](https://github.com/openshift/elasticsearch-operator/pull/481#issuecomment-690743106).
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1878032
/cc @ewolinetz @lukas-vlcek
=> Bug 1878032: Update cluster status after populating nodes

pkg/k8shandler/configmaps_test.go, pkg/k8shandler/configuration_tmpl.go
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1878305
By default, ES has a max header size of `8kb` which is too low for the case where it is behind a reverse proxy (in the case of our stack). This results in a `504` if trying to navigate to the Kibana exploration page, or a `400` if trying to access the Kibana status page.
Also fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1845293
=> Bug 1878305: Bump es max_header_size to address errors seen in Kibana

pkg/indexmanagement/reconcile.go, pkg/k8shandler/common.go, pkg/k8shandler/configmaps.go, pkg/k8shandler/dashboards.go, pkg/k8shandler/deployment.go, pkg/k8shandler/prometheus_rule.go, pkg/k8shandler/rbac.go, pkg/k8shandler/service.go, pkg/k8shandler/service_monitor.go, pkg/k8shandler/serviceaccount.go, pkg/k8shandler/statefulset.go
This PR addresses a mismatch in using `ownerReferences` for Elasticsearch CR dependents. Based on the following list the operator reconciler cluster-scoped dependents that poison the kubernetes gargbage collector cache. In turn the Elasticsearch CR and its namespace dependents get deleted as discussed in this upstream [PR](https://github.com/kubernetes/kubernetes/issues/65200) as well as noted on the [docs](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents).
Furthermore, this PR addresses missing `ownerReferences` for dashboard configmaps. It also cleanups duplicate usage of `addOwnerRefToObject` from `common.go` in favor of `AddOwnerRefTo` from `elasticsearch_types.go`.
```
"Service/elasticsearch"
"Service/elasticsearch-cluster" …
```
=> Bug 1880926: Fix owner references for elasticsearch CR

pkg/k8shandler/cluster.go, pkg/k8shandler/deployment.go, pkg/k8shandler/statefulset.go, pkg/k8shandler/status.go
This PR is addressing the case where deployments/statefulsets for Elasticsearch nodes are not existing although the last recorded status registered them as unschedulable. This event may happen during cluster upgrades where OCP cluster nodes become unavailable and in turn ES cluster nodes unschedulable for a period of time. During a cluster upgrade deployments/statefulset may get deleted and recreated because their owner references get deleted and recreated.
In more detail the implementation takes into account that deployments/statefulsets may not exist anymore and stops addressing them as unschedulable and re-creates anew. The rationale to re-create the nodes immediately in `progressUnschedulableNodes` is to bypass the need to actively change the node status from `Unschedulable` to …
=> Bug 1880926: Stop rescheduling non-existing nodes

pkg/k8shandler/configmaps_test.go, pkg/k8shandler/configuration_tmpl.go
Addresses comment https://bugzilla.redhat.com/show_bug.cgi?id=1883357#c2 (which is the 4.5 backport of bug referenced in PR title)
Further increasing the http.max_header_size above 16kb to 128kb
=> Bug 1878305: further increasing http max_header_size

files/prometheus_alerts.yml, files/prometheus_rules.yml
Bulk threadpool was renamed to index. See https://github.com/elastic/elasticsearch/pull/29593
/assign @blockloop
https://bugzilla.redhat.com/show_bug.cgi?id=1883719
=> Bug 1883719: Bulk statistics are recorded under index threadpool

pkg/elasticsearch/client.go, pkg/elasticsearch/replicas.go, pkg/elasticsearch/templates.go, pkg/k8shandler/cluster.go, pkg/k8shandler/configmaps.go, pkg/k8shandler/configuration_tmpl.go, pkg/k8shandler/defaults.go, pkg/k8shandler/defaults_test.go, pkg/k8shandler/elasticsearch.go, pkg/types/elasticsearch/types.go, test/utils/utils.go
Also updating reconcile loop to update the primary shard for index templates to ensure it accurately is reflected for new indices that are created.
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1883444
=> Bug 1883444: capping primary shard count at 5 for performance reasons

bundle/manifests/logging.openshift.io_kibanas_crd.yaml
This PR addresses the sync between our latest CRD state into our bundle manifest directory. This is mandatory to provide an up2date 4.6.0 bundle image.
- Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1884477
=> Bug 1884477: Update bundle manifests to reflect latest CRD state

pkg/k8shandler/status.go, pkg/k8shandler/status_test.go
This PR addresses the panics produced by in-place filtering the `status.Nodes` for missing Nodes field when iterating over it.
- Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1886796
=> Bug 1886796: Fix in-place filtering missing status nodes

pkg/k8shandler/common_test.go, pkg/k8shandler/defaults.go
The current default memory requests and limits for elasticsearch-proxy are set to 64Mi. This is a too tight budget according to metrics (see below):
In turn this results into container restarts that have impact on serving elasticsearch requests reliably. This PR addresses this issue by bumping the elasticsearch-proxy request/limits from `64Mi` to `256Mi`
- Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1886856
=> Bug 1886856: Increase es proxy default memory resources to 256Mi

pkg/apis/logging/v1/elasticsearch_types.go, pkg/k8shandler/common.go, pkg/k8shandler/common_test.go, test/e2e-olm/elasticsearch_test.go, test/e2e-olm/utils.go
This PR addresses a long-standing request to use the default cluster-wide storage class when the appropriate Elasticsearch CR field is undefined. The implementation is addressing this by making mandatory to set the field to an empty string if the user needs ephemeral storage. The following modes are now support for Elasticsearch CR users:
```
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
name: "instance"
namespace: "openshift-logging"
spec:
managementState: "Managed"
logStore:
type: "elasticsearch"
elasticsearch:
nodeCount: 1
storage:                  # <---- No storage class name provided here
size: 80Gi
redundancyPolicy: "ZeroRedundancy"
```
```
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
name: "instance"
namespace: "openshift-logging" …
```
=> Use default storageclass for elasticsearch pvc if none defined in CR

files/prometheus_alerts.yml
=> Bug 1886907: Flood stage watermark alert: Remove wording that read-only index block is auto-released

files/prometheus_alerts.yml, files/prometheus_rules.yml
Bulk threadpool was renamed to write. See elastic/elasticsearch#29593
https://bugzilla.redhat.com/show_bug.cgi?id=1883719
Fix of https://github.com/openshift/elasticsearch-operator/pull/511
/cc @blockloop
=> Bug 1883719: Bulk statistics are recorded under write threadpool

pkg/k8shandler/configmaps_test.go, pkg/k8shandler/configuration_tmpl.go
This PR modifies ES configuration to disallow auto-creation of indices with a "-write" suffix.  This will assist in upgrade scenarios to 4.5 where the new data model relies on "-write" aliases.  It additionally will help with situations where customers mismatch CLO and EO.  The outcome is they should find logs are not being pushed to the storage and errors generating in the collector but it will protect the data store and keep from additional action needed to "fix" bad indices
ref https://bugzilla.redhat.com/show_bug.cgi?id=1882495
cc @ewolinetz @mffiedler
=> Bug 1882495: Block auto index creation for indices with "-write" suffix

pkg/k8shandler/configuration_tmpl.go, pkg/k8shandler/confimaps_test.go
Manual cherrypick of:
* https://github.com/openshift/elasticsearch-operator/pull/502
* https://github.com/openshift/elasticsearch-operator/pull/508
To address: https://bugzilla.redhat.com/show_bug.cgi?id=1883357
By default, ES has a max header size of 8kb which is too low for the case where it is behind a reverse proxy (in the case of our stack). This results in a 504 if trying to navigate to the Kibana exploration page, or a 400 if trying to access the Kibana status page.
=> [release-4.5] Bug 1883357: Bump es max_header_size to address errors seen in Kibana

Makefile, bundle/manifests/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml, docs/HACKING.md
- the openshif-logging space may be unavailable
=> Examples: Allow deployment of es example in a different namespace

pkg/k8shandler/common.go, pkg/k8shandler/configmaps.go, pkg/k8shandler/deployment.go, pkg/k8shandler/prometheus_rule.go, pkg/k8shandler/rbac.go, pkg/k8shandler/service.go, pkg/k8shandler/service_monitor.go, pkg/k8shandler/serviceaccount.go, pkg/k8shandler/statefulset.go
This PR is a manual backport of #498. It removes all namespace-scoped owners from cluster-scoped resources' `ownerReferences` field. In turn this resolves random GC collection of Elasticsearch CR owned resources, e.g. deployments.
/cherry-pick release-4.4
- Depending on PR(s):  #498
- Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1883777
=> Bug 1883777: Fix owner references for elasticsearch CR

go.mod, go.sum, pkg/k8shandler/cluster.go, pkg/k8shandler/deployment.go, pkg/k8shandler/statefulset.go, pkg/k8shandler/status.go
This PR is a manual backport of #493. It addresses the case where deployments/statefulsets for Elasticsearch nodes are not existing although the last recorded status registered them as unschedulable. This event may happen during cluster upgrades where OCP cluster nodes become unavailable and in turn ES cluster nodes unschedulable for a period of time. The PR addresses this case by pruning the status fields in order to re-enable the deployment/statefulset recreation for the missing elasticsearch nodes.
/cherry-pick release-4.4
- Depending on PR(s):  #493
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1883777
=> Bug 1883777: Stop rescheduling non-existing nodes

go.mod, pkg/k8shandler/status.go, pkg/k8shandler/status_test.go, vendor/github.com/google/go-cmp/LICENSE, vendor/github.com/google/go-cmp/cmp/compare.go, vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go, vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go, vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go, vendor/github.com/google/go-cmp/cmp/internal/function/func.go, vendor/github.com/google/go-cmp/cmp/internal/value/format.go, vendor/github.com/google/go-cmp/cmp/internal/value/sort.go, vendor/github.com/google/go-cmp/cmp/options.go, vendor/github.com/google/go-cmp/cmp/path.go, vendor/github.com/google/go-cmp/cmp/reporter.go, vendor/github.com/google/go-cmp/cmp/unsafe_panic.go, vendor/github.com/google/go-cmp/cmp/unsafe_reflect.go, vendor/modules.txt
This PR is a manual backport of #525 and #531 and addresses the panics produced by in-place filtering the status.Nodes for missing Nodes field when iterating over it.
This backport drops the test-case `multi nodes prunning` in `status_test.go` because the `fake.Client` ([controller-runtime v0.1.10](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.1.10/pkg/client/fake/client.go#L103)) used in release-4.5 does not support the client-go `List` operation in combination with a label selectors used in `GetPodList`.
- Depending on PR(s):  #525 #531
- Bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1883777
=> Bug 1883777: Fix in-place filtering missing status nodes

pkg/k8shandler/cluster.go, pkg/k8shandler/common.go, pkg/k8shandler/persistentvolumeclaims.go, pkg/k8shandler/recovery.go, pkg/k8shandler/util.go, pkg/utils/resources.go
To address https://bugzilla.redhat.com/show_bug.cgi?id=1883355
Manual cherry-pick of #495
This addresses cases where there is or was an existing cluster created (deployments, pods, pvcs, etc) who's cluster name is the same as the CR name, however the new elasticsearch CR is missing UUIDs.
As part of the recovery/adoption process, it will be required that the PVCs to be picked back up have the label logging-cluster: . It will also be validated against the name of the cluster that the PVC name is based on.
Recovery/adoption will be triggered upon the processing of a CR that is missing UUIDs. It will only try to recover UUIDs for nodes that do not already have UUIDs defined.
Further documentation will need to be developed and publish as part of how to recover data that from another PVC. This …
=> [release-4.4] Bug 1883355: updating EO to adopt an existing cluster if cr nodes uuid is nil

olm_deploy/operatorregistry/Dockerfile
This PR reduces the size of the elasticsearch-operator-registry image from 1.1 GB to 333 MB:
```
$ podman image tree 127.0.0.1:5000/openshift/elasticsearch-operator-registry
Image ID: ed583fbe15c6
Tags:     [127.0.0.1:5000/openshift/elasticsearch-operator-registry:latest]
Size:     1.119GB
Image Layers
├──  ID: 613be09ab3c0 Size: 211.1MB
├──  ID: eb6dbe2d0eaa Size:   841MB Top Layer of: [registry.svc.ci.openshift.org/openshift/release:golang-1.12]
├──  ID: 48dd41eb413f Size: 70.66kB
├──  ID: ccb1fb4e4382 Size:  7.68kB
├──  ID: a272bb660edd Size: 4.096kB
├──  ID: 7454f954ce69 Size: 27.92MB
├──  ID: 321bfd15172e Size: 28.65MB
└──  ID: 363c3d1548ad Size:  9.93MB Top Layer of: [127.0.0.1:5000/openshift/elasticsearch-operator-registry:latest]
```
```
$ podman image tree …
```
=> Reduce the footprint of the elasticsearch-operator-registry image

pkg/controller/kibana/controller.go, test/e2e-olm/kibana_test.go, test/e2e-olm/utils.go
- fix unrecovered kibana route after being deleted
by Adding watch event for route and enqueue for the owner
- add a test case to e2e test
- fix unrecovered kibana route after being deleted
/assign @ewolinetz @blockloop 
/cherry-pick 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1890825
=> Bug 1890825: watch route deletion in kibana controller

pkg/k8shandler/service_monitor.go
This PR exposes the new es-proxy prometheus metrics endpoint to allow collection of these metrics by cluster-monitoring.
/cc @blockloop   
- Depending on PR(s):  openshift/elasticsearch-proxy#56
=> LOG-967: Add service monitor endpoint for es-proxy prometheus metrics

.github/pull_request_template.md, docs/HACKING.md, manifests/4.7/elasticsearch-operator.v4.7.0.clusterserviceversion.yaml
This PR:
* Updates the csv example and correcting the Provider to match CLO.
* Updates the docs/hacking.md file to be more relevant to the current development and deployment process with make targets
* Minor typo in the pull_request_template
- JIRA: https://issues.redhat.com/browse/LOG-900
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1891666
=> Bug 1891666: LOG-900: Updating hacking docs and csv to be more up-to-date

Makefile
Remove fmt from make build because it breaks ART
/cc @periklis 
=> Remove fmt from make build because it breaks ART

Makefile, test/files/prometheus-unit-tests/test.yml
Facilitating `promtool` to add unit-tests for Elasticsearch Prometheus alerts.
- JIRA: https://issues.redhat.com/browse/LOG-939
=> LOG-939: Add Prometheus unit testing

pkg/k8shandler/cluster.go, pkg/k8shandler/status.go
Adding crashloopbackoff to list of conditions for unschedulable nodes.
Cherry-picking logic that originally was introduced in https://github.com/openshift/elasticsearch-operator/pull/400
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1891019
=> Bug 1891019: Adding logic to recover from crashloopbackoff for ES pods

pkg/k8shandler/service.go, pkg/k8shandler/service_test.go
This PR addresses a switch from the alpha to beta annotation of `service.beta.openshift.io/serving-cert-secret-name`. This annotation serves for injecting the prometheus CA certificate for the annotated service resource.
- JIRA: https://issues.redhat.com/browse/LOG-951
=> LOG-951: Replace alpha svc annotation with beta

pkg/k8shandler/index_management.go
Updating index template logic to correctly use function to calculate primary shards instead of just counting data nodes
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1883444
=> Bug 1883444: Updating index template logic to cap primary shards

pkg/k8shandler/kibana/reconciler.go, pkg/k8shandler/kibana/route.go, test/e2e-olm/kibana_test.go
Currently it is possible for a `kibana` resource that is created by a developer in a non `openshift-logging` namespace to cause the console links to be recreated based on this new CR. Likewise, when this `kibana` resource is removed we lose the `openshift-logging` console links.
This PR seeks to restrict the creation of these to just the ClusterLogging use case (since that use case is what provides fluentd and log aggregation for the cluster).
/cc @blockloop @periklis @lukas-vlcek 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1898572
=> Bug 1898572: Restricting console links to clusterlogging operator use case

Makefile, pkg/k8shandler/common.go, pkg/k8shandler/common_test.go
The size field for logging storage should have been marked as required, if we did not provide it we would receive a panic from a null pointer. This PR seeks to make it required at the CRD level, as well as have fall back in the event cr creation/update makes it past CRD validation.
/cc @blockloop @periklis
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1899589
=> Bug 1899589: Updating CRD to make storage size required if storage is provided

Makefile, pkg/k8shandler/kibana/kibana_test.go
This PR provides a small fix for the broken kibana/consolelink unit tests. The unit tests did not report failure because of the missing `pipefail` setting.
/cc @huikang 
- Bugzilla:
=> Bug 1898572: Fix kibana unit tests

pkg/k8shandler/rbac.go
Manual cherry-pick to remove ownerrefs from our clusterscoped objects.
/cc @jcantrill @blockloop 
- Depending on PR(s): https://github.com/openshift/elasticsearch-operator/pull/506
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1906584
=> [release-4.4] Bug 1906584: Removing ownerrefs from cluster scoped objects to address GC issue

Dockerfile.centos.patch, Makefile
`make image` now uses a CentOS base image. This shouldn't affect the upstream builds because the original Dockerfile is untouched. This _does_ however, change the default make target to use the new Dockerfile.dev which is based on CentOS. 
/cc @lukas-vlcek @vimalk78 
- JIRA: [LOG-970](https://issues.redhat.com/browse/LOG-970)
=> LOG-970: use centos as base image for docker

bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml, config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml, manifests/5.0/elasticsearch-operator.v5.0.0.clusterserviceversion.yaml
This PR addresses a small glitch in generation CSV manifests for upcoming version 5.0. In detail it omits using the `replace` directive in the CSV spec to enable QE importing unreleased operators using the `opm` CLI tool.
/cc @huikang 
/assign @jcantrill  
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1906895
=> Bug 1906895: Remove replace directive in 5.0 CSV manifest

internal/k8shandler/configmaps_test.go, internal/k8shandler/configuration_tmpl.go
This PR addresses missing access rights for the `kibana_server` opendisto security role to allow kibana access the `_opendistro/_security/tenantinfo` API path. I.e.:
The Kibana opendistro security plugin includes a migration step for user tenants which requires access to the internal opendistro security API. The approach used follows the steps:
1. OpenDistro Security Plugin initializes a ES client to access `_opendistro/_security`.
2. This client is using the `elasticsearch.username: "CN=system.logging.kibana,OU=OpenShift,O=Logging"` from `kibana.yml` as its internal user to access Elasticsearch.
3. The subject `CN=system.logging.kibana,OU=OpenShift,O=Logging` maps to the role `kibana_server`
4. This role is not enabled in `opendistro_security.restapi.roles_enabled:` and kibana fails to …
=> Bug 1885723: Allow kibana server to access OD tenantinfo

internal/elasticsearch/client.go, internal/elasticsearch/replicas.go
This PR addresses a false negative error log in ES nodes logs. The culprit is the elasticsearch-operator trying to update `.security/_settings/index.number_of_replicas` setting. Such calls are currently only allowed using the admin cert/key PR directly to elasticsearch (e.g. like in `es_seed_acl`). This fix is not a downgrade in operating multiple replicas of the `.security` index. The ES init procedure for the `.security` index takes care to set the replicas to `1` if the ES cluster has more than one node.
Needs backports for: **release-4.6** and **release-4.5**
/cc @huikang 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1907758
=> Bug 1907758: Fix update replica count for logging indices only

pkg/k8shandler/configmaps_test.go, pkg/k8shandler/configuration_tmpl.go
This PR is a manual backport of #603 .
This change set addresses missing access rights for the `kibana_server` opendisto security role to allow kibana access the `_opendistro/_security/tenantinfo` API path. I.e.:
The Kibana opendistro security plugin includes a migration step for user tenants which requires access to the internal opendistro security API. The approach used follows the steps:
1. OpenDistro Security Plugin initializes a ES client to access `_opendistro/_security`.
2. This client is using the elasticsearch.username: `CN=system.logging.kibana,OU=OpenShift,O=Logging` from `kibana.yml` as its internal user to access Elasticsearch.
3. The subject `CN=system.logging.kibana,OU=OpenShift,O=Logging` maps to the role kibana_server
4. This role is not enabled in …
=> [release-4.6] Bug 1909614: Allow kibana server to access OD tenantinfo 

manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
Manual cherrypick of https://github.com/openshift/elasticsearch-operator/pull/579
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1901299
=> [release-4.6] Bug 1901299: Change ES Operator CSV to clarify the scope for this Operator

files/prometheus_alerts.yml, test/files/prometheus-unit-tests/test.yml
Includes a warning-level alert for when the elasticsearch-operator CSV's phase is not "success". ie: when `csv_success{name =~ "elasticsearch-operator.*"} == 0`.
We (OpenShift SRE-P) will configure alertmanager to suppress our alert-level alerts for ElasticsearchClusterNotHealthy while this alert is active.
/cc @alanconway
- JIRA: https://issues.redhat.com/browse/OSD-5685
=> Bug 1913464: configure a warning level alert for when the CSV phase isn't success

controllers/logging/elasticsearch_controller.go, internal/k8shandler/dashboards.go
- Fix cross-namespace owner reference for the configmap
- Remove configmap after CR being deleted
OCP 4.7 (k8s v1.20) does not allow cross-namespace owner reference. So the configmap is garbage collected due to invalid reference. This PR fixes the issue.
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1910259
=> Bug 1910259: Fix missing grafana dashboard in OCP 4.7

files/prometheus_alerts.yml, test/files/prometheus-unit-tests/test.yml
`ElasticsearchClusterNotHealthy` is one of the noisier alerts on OSD. After reviewing this alert we found that this alert "self resolves" most commonly after 5 minutes.
Setting this to 7 minutes should relieve this.
/cc @alanconway
- JIRA: https://issues.redhat.com/browse/OSD-5889
- Bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1908958 4.7
https://bugzilla.redhat.com/show_bug.cgi?id=1908959 4.6
=> Bug 1908958: Change ElasticsearchClusterNotHealthy to 7 minutes

.gitignore, Dockerfile.centos.patch, Makefile, docs/HACKING.md
This is a baby step towards making the makefile use real targets that only execute
when something is changed. This creates a new pattern for targets that do not 
produce a file on the disk. For any target that does not create a filesystem target
add `@touch $@` to the end of the target and map the target to `.output/<target_name>`
For example:
```
image: .output/image
.output/image: <prereqs here | this part is very important>
podman build -t <etc etc>
@touch $@
```
=> force make image to be a real target

internal/indexmanagement/scripts.go
Hardening the rollover script called by the indexmanagement rollover cronjob.
This will now check if the rollover was successful based on the current write index.
If it was not, determine what the next index would be
For both success and failure we check:
1) Was the next index created
2) Does the write alias point to this index
If it does not point to it, we update the write alias.
/cc @lukas-vlcek @blockloop 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1893992
=> Bug 1893992: Improve elasticsearch indexmanagement rollover script

files/prometheus_alerts.yml, test/files/prometheus-unit-tests/test.yml
Fix the url link to the alert page: "md.md" should be ".md"
/assign @ewolinetz @blockloop 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1913469
=> Bug 1913469: fix link to the alert page

internal/indexmanagement/reconcile.go, internal/indexmanagement/reconcile_test.go, internal/k8shandler/index_management.go
This PR collapses the multiple policy cronjobs to a single job with multiple tasks it runs:
* delete
* rollover
The reasoning is there is a potential race condition between the previous jobs which both rely upon a `-write` alias that may lead to false information.  Additionally, ES does not have transactions or is ACID.  By converting these into tasks we execute for management we:
* potentially free disk for ES to do additional work
* give a better chance for the rollover to be successful
* May need to add a task to "unblock" the read-only index identified in the BZ
One risk in this proposed solution is failure of the first container will block any subsequent behaviors.  Placing the PR on hold pending agreement its a viable solution
/cc @lukas-vlcek @periklis 
/assign  @ewolinetz 
/assign …
=> Bug 1890838: Condense indexmanagement into single cronjob

pkg/k8shandler/index_management.go
Updating index template logic to correctly use function to calculate primary shards instead of just counting data nodes
Manual cherrypick of https://github.com/openshift/elasticsearch-operator/pull/574
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1885667
=> [release-4.6] Bug 1885667: Updating index template logic to cap primary shards

files/prometheus_alerts.yml, test/files/prometheus-unit-tests/test.yml
(cherry picked from commit 7ca1656d436e07843855b56a8bdce681e8872dea)
ElasticsearchClusterNotHealthy is one of the noisier alerts on OSD. After reviewing this alert we found that this alert "self resolves" most commonly after 5 minutes.
Setting this to 7 minutes should relieve this.
cc @ewolinetz @blockloop 
Backport of https://github.com/openshift/elasticsearch-operator/pull/600
https://bugzilla.redhat.com/show_bug.cgi?id=1908959
=> Bug 1908959: Change ElasticsearchClusterNotHealthy to 7 minutes

pkg/indexmanagement/reconcile.go, pkg/indexmanagement/reconcile_test.go, pkg/k8shandler/index_management.go, pkg/log/log.go
(cherry picked from commit c7079ed90bc0fbe76bad0871d7dbb1eab091af5f)
This PR collapses the multiple policy cronjobs to a single job with multiple tasks it runs:
* delete
* rollover
* adds simple adapter to log package to facilitate cherrypicks from post 4.6
The reasoning is there is a potential race condition between the previous jobs which both rely upon a `-write` alias that may lead to false information.  Additionally, ES does not have transactions or is ACID.  By converting these into tasks we execute for management we:
* potentially free disk for ES to do additional work
* give a better chance for the rollover to be successful
* May need to add a task to "unblock" the read-only index identified in the BZ
4.6 backport of …
=>  Bug 1916910: Condense indexmanagement into single cronjob

pkg/k8shandler/kibana/kibana_test.go, pkg/k8shandler/kibana/reconciler.go, pkg/k8shandler/kibana/route.go, test/e2e-olm/kibana_test.go
Manual cherry-pick of
* https://github.com/openshift/elasticsearch-operator/pull/581
* https://github.com/openshift/elasticsearch-operator/pull/587
/cherry-pick release-4.5
- Depending on PR(s): 
https://github.com/openshift/elasticsearch-operator/pull/581
https://github.com/openshift/elasticsearch-operator/pull/587
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1902768
=> [release-4.6] Bug 1902768: Restricting console links to clusterlogging operator use case

pkg/controller/elasticsearch/controller.go, pkg/k8shandler/dashboards.go
Manual cherry-pick of #610
We have same issue when deploy logging 4.6 on a 4.7 OCP cluster. After OCP 4.7 GA, if customers upgrade their OCP version to 4.7 but don't upgrade logging, then they will hit this issue.
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1914987
=>  [release-4.6] Bug 1914987: Fix missing grafana dashboard upgrading to 4.7

apis/logging/v1/elasticsearch_types.go, internal/k8shandler/reconciler.go, internal/k8shandler/status.go, main.go
No longer block rest of configuration if prom errors occur -- will be marked as Degraded
/cc @lukas-vlcek @blockloop 
example output:
```
status:
cluster:
activePrimaryShards: 8
activeShards: 16
initializingShards: 0
numDataNodes: 3
numNodes: 3
pendingTasks: 0
relocatingShards: 0
status: green
unassignedShards: 0
conditions:
- lastTransitionTime: "2021-01-21T21:25:06Z"
message: 'failed to build prometheus rule: failed to open file: open /etc/elasticsearch-operator/files/prometheus_recording_rules_bad.yml:
no such file or directory'
reason: Missing Prometheus Rules
status: "True"
type: Degraded
nodes:
- deploymentName: elasticsearch-cdm-od99jfcc-1
upgradeStatus: {}
- deploymentName: elasticsearch-cdm-od99jfcc-2
upgradeStatus: {}
- deploymentName: elasticsearch-cdm-od99jfcc-3
upgradeStatus: …
```
=> LOG-1030: Adding degraded state to ES cluster status for prometheus case

internal/constants/constants.go, internal/elasticsearch/templates.go, internal/k8shandler/index_management.go, internal/k8shandler/index_management_test.go
Before:
the IndexManagement logic would create and reseed the generated index templates and we also were updating existing index templates in another location.
With this PR:
EO only creates the initial index template if it does not yet exist on the cluster. All index template (idempotent) update logic co-located and only occurring when a cluster restart is not in progress.
/cc @lukas-vlcek @blockloop 
- JIRA: https://issues.redhat.com/browse/LOG-1018
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1920215
=> Bug 1920215: LOG-1018: Updating IndexManagement to only create initial index template

controllers/logging/secret_controller.go, internal/k8shandler/deployment.go, internal/k8shandler/nodetypefactory.go, internal/k8shandler/reconciler.go, internal/k8shandler/statefulset.go, main.go
Add a controller to watch changes to ES's secret
- Predicate returns true if the updated secret name matches any cluster's name/namespace
- compare the hash content of the secret. if changed, mark the node status to "restart"
/cc @ewolinetz @jcantrill 
- JIRA: https://issues.redhat.com/browse/LOG-1009
=> Bug 1918920: [LOGEXP 1009] Watch secret update for elasticsearch cluster

internal/constants/constants.go, internal/k8shandler/reconciler.go, internal/k8shandler/secret.go
Adding `Degraded` condition for when we are missing required secret/fields for communicating with Elasticsearch.
This degraded condition will take priority over the current missing prometheus alerts since EO not being able to communicate with ES means the operator cannot perform any operations on the cluster.
Missing field(s):
```
conditions:
- lastTransitionTime: "2021-02-09T22:36:37Z"
message: 'Secret "elasticsearch" fields are either missing or empty: [admin-ca,
admin-cert, admin-key]'
reason: Missing Required Secrets
status: "True"
type: Degraded
```
Missing secret:
```
conditions:
- lastTransitionTime: "2021-02-09T22:03:42Z"
message: Expected secret "elasticsearch" in namespace "openshift-logging" is missing
reason: Missing Required Secrets
status: "True"
type: Degraded
```
/cc …
=> LOG-959: Adding degraded condition for when we are missing the required secret/fields for ES

pkg/constants/constants.go, pkg/elasticsearch/templates.go, pkg/k8shandler/index_management.go, pkg/k8shandler/index_management_test.go, pkg/k8shandler/migrations/pvc_naming.go
Manual cherry-pick of #632 
Before:
the IndexManagement logic would create and reseed the generated index templates and we also were updating existing index templates in another location.
With this PR:
EO only creates the initial index template if it does not yet exist on the cluster. All index template (idempotent) update logic co-located and only occurring when a cluster restart is not in progress.
/cc @huikang 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1923791
=> Bug 1923791: Updating IndexManagement to only create initial index template

bundle/manifests/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
This PR provides a small fix in the ClusterServiceVersion deployment manifest for the elasticsearch-operator. The fix provides the correct container ports to expose http and cr metrics as expected by OLM-managed deployments.
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1924657
=> Bug 1924657: Fix metrics ports exposed by operator deployment

Makefile, hack/testing-olm-upgrade/upgrade-common, olm_deploy/scripts/catalog-deploy.sh, olm_deploy/scripts/registry-init.sh
This PR
* removes IMAGE_FORMAT in deference to images defined via env vars
* IMAGE_FORMAT has been deprecated for over a year
* CI was modified to tag in image refs via "pipelines" that are consumable by env vars
* update dev imagestream to be "logging"
/cc @periklis @vimalk78 @ewolinetz 
/cherrypick release-5.0
/cherrypick tech-preview
=> use image env vars instead of IMAGE_FORMAT

internal/elasticsearch/client.go
Due to the fact that the elasticsearch operator can manage multiple ES cluster in multiple namespaces we need to ensure that the CA we store and use is unique to the cluster we are currently connecting to. Currently we just store based on cluster name, which can be reused in multiple namespaces.
/cc @blockloop
=> Updating local cert storage path to be unique based on namespace and cluster name

pkg/indexmanagement/reconcile.go, pkg/indexmanagement/reconcile_test.go, pkg/k8shandler/index_management.go, pkg/log/log.go
This PR collapses the multiple policy cronjobs to a single job with multiple tasks it runs:
* delete
* rollover
* adds simple adapter to log package to facilitate cherrypicks from post 4.6
The reasoning is there is a potential race condition between the previous jobs which both rely upon a -write alias that may lead to false information. Additionally, ES does not have transactions or is ACID. By converting these into tasks we execute for management we:
* potentially free disk for ES to do additional work
* give a better chance for the rollover to be successful
May need to add a task to "unblock" the read-only index identified in the BZ
/cc @ewolinetz
backport of 4.6 https://github.com/openshift/elasticsearch-operator/pull/627
https://bugzilla.redhat.com/show_bug.cgi?id=1919075
=> Bug 1919075: Condense indexmanagement into single cronjob

hack/testing-olm-upgrade/upgrade-common
This PR provides a minor fix for the elasticsearch-operator E2E upgrade suite. The suite was broken by changing the release schema from OCP to OpenShift Logging, i.e. switching from 4.6 to 5.x
/cc @vimalk78 
- JIRA: https://issues.redhat.com/browse/LOG-1182
=> Fix upgrade tests for release-5.0

controllers/logging/elasticsearch_controller.go, internal/k8shandler/cluster.go, internal/metrics/metrics.go, main.go
This PR:
- Exposes custom metrics which can be scraped by monitoring prometheus.
- This can be queried via the OCP dashboard (Monitoring -> Metrics).
/cc @periklis 
- JIRA: https://issues.redhat.com/browse/LOG-316
=> Log-316: Elasticsearch Operator Telemetry

bundle/manifests/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml, bundle/manifests/logging.openshift.io_kibanas_crd.yaml, manifests/4.6/elasticsearch-operator.v4.6.0.clusterserviceversion.yaml
This PR provides a small fix in the ClusterServiceVersion deployment manifest for the elasticsearch-operator. The fix provides the correct container ports to expose http and cr metrics as expected by OLM-managed deployments.
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1924657
=> Bug 1924657: Fix missing metrics port in manifests and bundle

internal/indexmanagement/scripts.go
In anticipation for the ability to store json in Elasticsearch, we need to be able to rollover and delete any json specific write alias based on the policy for either `app`, `infra`, or `audit` (json indices/aliases will follow the pattern `<app|infra|audit>-<json-schema-name>-<write|xxxxxx>`)
Also cleaned up output of the delete and rollover scripts for ease of use:
```
========================
Index management delete process starting for infra-json
deleting indices: infra-json-000055
Done!
========================
Index management delete process starting for infra
deleting indices: infra-000074
Done!
========================
Index management rollover process starting for infra-json
Current write index for infra-json-write: infra-json-000057
Checking results from _rollover call
Next …
```
=> LOG-1153: Adding logic to perform rollover and delete for json write indices

bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml, config/manager/manager.yaml, manifests/5.0/elasticsearch-operator.v5.0.0.clusterserviceversion.yaml
Resolves regression seen in https://bugzilla.redhat.com/show_bug.cgi?id=1939979 where we introduce a resource request/limit for the elasticsearch operator.
/cc @vimalk78 @jcantrill 
Manual cherrypick of https://github.com/openshift/elasticsearch-operator/pull/683
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1939979
=> [release-5.0] Removing resource request and limits from EO deployment definition

apis/logging/v1/elasticsearch_types.go, bundle/manifests/logging.openshift.io_elasticsearches.yaml, config/crd/bases/logging.openshift.io_elasticsearches.yaml, manifests/5.1/logging.openshift.io_elasticsearches_crd.yaml
This PR is the rebased version of this one: https://github.com/openshift/elasticsearch-operator/pull/630
/cc @periklis  
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1916911
=> Bug 1916911: make es status nullable for nodes and pods

apis/logging/v1/elasticsearch_types.go, bundle/manifests/logging.openshift.io_elasticsearches.yaml, config/crd/bases/logging.openshift.io_elasticsearches.yaml, manifests/5.0/logging.openshift.io_elasticsearches_crd.yaml
Manual cherry pick of: https://github.com/openshift/elasticsearch-operator/pull/686
Fix crd incompability during upgrading from 4.5 to 4.6
=> Bug 1946776: fix es crd status incompatible when upgrading operator

Dockerfile, Dockerfile.centos.patch
Slimming our operator image to only copy over necessary files for building our binary and running the operator in a cluster.
- Github issue: https://github.com/openshift/elasticsearch-operator/issues/635
=> Updating dockerfile to just copy necessary files for building image

docs/alerts.md
This PR:
- Ensures that critical alerts have proper diagnostic steps and action steps.
- JIRA: https://issues.redhat.com/browse/LOG-1098
=> Log 1098 - Playbook for Critical Alerts

docs/pvc-recovery.md, internal/k8shandler/configmaps_test.go, internal/k8shandler/configuration_tmpl.go
Changing the Elasticsearch configuration to use PKCS12 format instead of JKS. As far as I can tell, it does not matter if JKS is already running or not (though when I changed the config map, I don't think I noticed my pod restarting).
- JIRA: https://issues.redhat.com/browse/LOG-958
=> ES configuration uses PKCS12 format instead of JKS

apis/logging/v1/elasticsearch_types.go, internal/k8shandler/deployment.go, internal/k8shandler/podtemplate.go, internal/k8shandler/statefulset.go, internal/k8shandler/status.go, main.go
This PR adds the following capabilities:
- Adds a condition when the storage volume JSON structure has changed
- Adds a condition when the storage class name has changed
- Adds a condition when the size of the storage has changed
- Ignores changes to the volume deployment
- JIRA: https://issues.redhat.com/browse/LOG-920
=> Adding storage volume conditions to Elasticsearch

apis/logging/v1/elasticsearch_types.go, internal/elasticsearch/client.go, internal/elasticsearch/indices.go, internal/k8shandler/index_management_test.go, internal/k8shandler/migrations/kibana5to6.go, internal/k8shandler/migrations/kibana5to6_test.go, internal/k8shandler/status.go, internal/types/elasticsearch/types.go
This PR:
- Fixes the struct used for Index Setting API
The response of Index Setting API is:
> ".security" : {
"settings" : {
"index" : {
"number_of_shards" : "1",
"provided_name" : ".security",
"creation_date" : "1617190076948",
"number_of_replicas" : "0",
"uuid" : "Mcjw5XDXQai84jjcUjNIkA",
"version" : {
"created" : "6080199"
}
}
}
}
The above respose was getting parsed wrongly into the struct and was returning `nil` values.
- Minor fmt fixes
/cc @periklis @lukas-vlcek 
=> Api struct fixes and fmt fixes

Makefile, internal/elasticsearch/client.go, internal/elasticsearch/replicas.go, internal/k8shandler/cluster.go, internal/k8shandler/status.go, internal/k8shandler/util.go, internal/k8shandler/util_test.go
To help protect user data more, we want to prevent users from making dangerous configuration changes when it comes to scaling down the number of ES nodes deployed to the cluster.
Based on the current minimum number of replicas for the cluster (not the redundancy policy) we determine the maximum number of nodes we can scale down at a time to help prevent data loss.
/cc @lukas-vlcek @blockloop @periklis 
- JIRA: https://issues.redhat.com/browse/LOG-981
=> LOG-981: rate limit es cluster downsizings to limit data loss

controllers/logging/secret_controller.go, internal/k8shandler/reconciler.go
Manual cherrypick of https://github.com/openshift/elasticsearch-operator/pull/667 and https://github.com/openshift/elasticsearch-operator/pull/695
/cc @periklis 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1952968
=> Bug 1952968: Allow secret reconciler to reconcile during create

docs/troubleshooting.md
Document techniques to pull number of logs per project.
=> Query to pull number of logs per project

pkg/k8shandler/kibana/reconciler.go
This PR provides a small fix for OCP environments with custom internal DNS, where using `cluster.local` for accessing Elasticsearch from Kibana is not valid.
**Note:** Needs porting to 5.0.x and 5.1.x
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1945168
=> Bug 1945168: Remove hardcoded cluster local domain

internal/k8shandler/kibana/reconciler.go
This PR provides a port of the merged fix #691 (Target Version `4.6.z`) for `5.1.0`
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1945168
- JIRA: https://issues.redhat.com/browse/LOG-1327
=> LOG-1327: Port fix to 5.1.0 for BZ-1945168

docs/alerts.md, files/prometheus_alerts.yml, test/files/prometheus-unit-tests/test.yml
This PR:
- Adds warning alert for low, high and flood disk watermark thresholds
- The thresholds are predicted by taking data of past 3h and alerted if it is expected to cross the threshold within next 6h
- To avoid false positives, the alert will be fired only if it stays active for 1h
- Added unit test to verify the alert
- Added playbook for low disk watermark
- JIRA: https://issues.redhat.com/browse/LOG-1100
=> Log-1100: Warning alerts to prevent users from reaching disk watermark thresholds

internal/k8shandler/kibana/reconciler.go
This PR provides a port of the merged fix #691 (Target Version `4.6.z`) for `5.0.z`
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1945168
- JIRA: https://issues.redhat.com/browse/LOG-1328
=> LOG-1328: Port fix to 5.0.z for BZ-1945168

Dockerfile, Dockerfile.dev, Dockerfile.in, dev-meta.yaml, files/prometheus_alerts.yml, go.mod, hack/generate-dockerfile-from-midstream, internal/k8shandler/prometheus_rule.go, internal/k8shandler/prometheus_rule_test.go, origin-meta.yaml, test/files/prometheus-unit-tests/test.yml, vendor/modules.txt
For upstream and downstream, we use different URLs for our playbooks.
This will need to be cherrypicked to 5.1 as well
/cc @periklis @lukas-vlcek
- Related to PR(s): https://github.com/openshift/openshift-docs/pull/32586
- JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2791
=> LOG-1380: Updating alerts to use runbook_url and have different base URIs

Dockerfile, Dockerfile.dev, Dockerfile.in, dev-meta.yaml, files/prometheus_alerts.yml, go.mod, hack/generate-dockerfile-from-midstream, internal/k8shandler/prometheus_rule.go, internal/k8shandler/prometheus_rule_test.go, origin-meta.yaml, test/files/prometheus-unit-tests/test.yml, vendor/modules.txt
For upstream and downstream, we use different URLs for our playbooks.
Manual cherry-pick of https://github.com/openshift/elasticsearch-operator/pull/717
/cc @jcantrill
=> Updating alerts to use runbook_url and have different base URIs

internal/k8shandler/cluster.go
This PR:
- Fixes the issue of `eo_elasticsearch_cr_restart_total{reason="rolling_restart"}` not getting incremented sometimes while the ES cluster performs rolling restart.
The metric wasn't getting incremented because when the ES cluster is scheduled for rolling restart, it doesn't finish the restart in the same iteration most of the time and hence the scheduled node goes into `inProgress` state. The restart becomes successful in subsequent iterations and hence the metric should be incremented when `inProgress` nodes have restarted successfully additional to when the restart becomes successful in the first iteration itself.
/cc @QiaolingTang 
- JIRA: https://issues.redhat.com/browse/LOG-1309
=> LOG-1309: Sometimes the metric count "rolling_restart" doesn't increase after ES cluster perform rolling restart.

internal/k8shandler/cluster.go
This PR:
- Updates the EO to check for watermark and unblock indices only when all elasticsearch nodes are ready 
- JIRA: https://issues.redhat.com/browse/LOG-1406
=> LOG-1406: Check for watermark and unblock indices only when all nodes are ready

internal/k8shandler/deployment.go, internal/k8shandler/podtemplate.go, internal/k8shandler/podtemplate_test.go, internal/k8shandler/statefulset.go, internal/k8shandler/status.go
Prevents the ES cluster from upgrading when a user is making an unsupported change to the storage spec. This also fixes the ephemeral to persistent volume claim case. 
As a note, this PR also makes the `StorageStructureChangeIgnored` status appear when the cluster is first spinning up. However, this status will disappear before the cluster goes `green`. The status will then not appear unless the user attempts to add storage after the cluster has been created.
In order to remove this condition when the user has attempted to add storage, the user must remove the PVC that is created by their change. This PVC will be stuck in the pending state as the cluster will not actually make the PV accompanying it, since it will overwrite those expected changes with the original volumes. Once the user …
=> LOG-1351: Preventing upgrade when changes done to the storage

internal/k8shandler/cluster.go
This PR:
- Is the backport to release-5.1 for the previous PR (https://github.com/openshift/elasticsearch-operator/pull/714)
/cc @QiaolingTang
JIRA: https://issues.redhat.com/browse/LOG-1309
=> [release-5.1] LOG-1309: Sometimes the metric count "rolling_restart" doesn't increase after ES cluster perform rolling restart.

internal/indexmanagement/scripts.go
The fix provided ensures that the rollover job is aborted with a failure exit code when the target index exists but is read-only. In various situations (e.g. low on disk space) the ES cluster can decide to put indices into read-only until a human operator takes action to expand disk volume.
/cherry-pick release-5.1
/cherry-pick release-5.0
- JIRA: https://issues.redhat.com/browse/LOG-1273
=> Abort rollover when target index exists but read-only

bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml, config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml, internal/k8shandler/podtemplate.go, manifests/5.1/elasticsearch-operator.v5.1.0.clusterserviceversion.yaml
Update the operator to identify infrastructure features:
* disconnected
* proxy-aware
* https://issues.redhat.com/browse/LOG-1458
* https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs
=> LOG-1458: Annotate with infrastructure features

bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml, config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml, internal/k8shandler/podtemplate.go, manifests/5.2/elasticsearch-operator.v5.2.0.clusterserviceversion.yaml
Update the operator to identify infrastructure features:
* disconnected
* proxy-aware
* https://issues.redhat.com/browse/LOG-1420
* https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs
@ewolinetz  I believe this applies to EO as well.  I may need to clone this issue specifically for EO and its backports for QE validation
=> LOG-1420: Annotate with infrastructure features

hack/testing-olm-upgrade/resources/cr.yaml
This PR provides a small fix for the default storage class name used in E2E upgrade tests for the `Elasticsearch` custom resource.
=> Fix storage class for e2e-upgrades running on GCP

internal/k8shandler/deployment.go, internal/k8shandler/statefulset.go, test/e2e-olm/elasticsearch_test.go
The following change set provides a fix for the full cluster redeploy scenario with non-data ES nodes. The cause of this bug is that the elasticsearch-operator is using the wrong CR spec when updating the replica count to zero. This causes a full cluster redeploy being stuck in the scale down step forever. In turn no full cluster redeploy completes and leaves the ES cluster in an unhealthy state.
/cherry-pick release-5.1
/cherry-pick release-5.0
- JIRA: https://issues.redhat.com/browse/LOG-1524
=> LOG-1524: Fix full cluster cert redeploy with non-data nodes

internal/k8shandler/deployment.go, internal/k8shandler/statefulset.go, test/e2e-olm/elasticsearch_test.go
This is a manual cherry-pick of #740 and obsoletes cherry-pick-bot-created #741. Cherry-pick bot created a PR which is missing the manual step to create elasticsearch certificates in `release-5.1`. In comparison master a.k.a. `release-5.2` provides a mechanism to let elasticsearch-operator manages ES certificates 
- JIRA: https://issues.redhat.com/browse/LOG-1536
=> [release-5.1] LOG-1536: Fix full cluster cert redeploy with non-data nodes 

internal/indexmanagement/index_management_test.go, internal/indexmanagement/reconcile.go, internal/indexmanagement/reconcile_test.go, internal/manifests/cronjob/build.go
The following PR provides a fix to suspend the Index management cronjobs when ES cluster is shut down. Suspending the cronjobs prevents them to run till `BackoffLimitExceeded` which in turn requires manual cronjob removal.
- JIRA: https://issues.redhat.com/browse/LOG-1268
=> LOG-1268: Suspend cronjobs when ES is scaled to zero nodes

internal/indexmanagement/reconcile.go, internal/indexmanagement/reconcile_test.go, internal/indexmanagement/scripts.go
This PR is a follow-up on #726 to fix the exit code handler for combined execution of rollover and delete scripts in a single cronjob run. The following cmd used before didn't handle the exit code properly and defaults always to exit code 0:
```
./delete;delete_rc=$?;./rollover;rollover_rc=$?;$(exit $delete_rc&&exit$rollover_rc)
```
- JIRA: https://issues.redhat.com/browse/LOG-1273
=> LOG-1273: Fix cronjob exit code handler for combined delete and rollover exec

internal/indexmanagement/reconcile.go, internal/indexmanagement/reconcile_test.go, internal/k8shandler/index_management.go, internal/k8shandler/index_management_test.go
This is a manual backport of #723 to introduce suspending indexmanagement cronjobs when no elasticsearch nodes available. 
- JIRA: https://issues.redhat.com/browse/LOG-1552
=> LOG-1552: Suspend cronjobs when ES is scaled to zero nodes

internal/indexmanagement/scripts.go
This PR:
- Fixes the issue of using wrong `nextIndex` variable in `updateWriteIndex` function.
/cc @periklis 
Jira: https://issues.redhat.com/browse/LOG-1567
=> LOG-1567: Use correct variable for nextIndex

bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml, docs/HACKING.md, hack/common, internal/constants/constants.go, internal/kibana/defaults.go, manifests/5.2/elasticsearch-operator.v5.2.0.clusterserviceversion.yaml, olm_deploy/scripts/registry-init.sh
This PR provides several fixes for our upstream aka origin images hosted in 5.x under `quay.io/openshift-logging`.
/cc @igor-karpukhin 
=> Fix upstream origin images

go.mod, go.sum, vendor/github.com/ViaQ/logerr/LICENSE, vendor/github.com/ViaQ/logerr/log/encoding.go, vendor/github.com/ViaQ/logerr/log/logger.go, vendor/modules.txt
This PR addresses the missing LICENSE file in the `viaq/logerr` dependency. 
/cc @igor-karpukhin 
/assign @igor-karpukhin
=> LOG-1590: Bump viaq/logerr to v1.0.10

olm_deploy/operatorregistry/elasticsearch-operator.package.yaml, olm_deploy/scripts/operator-install.sh
This PR addresses some preparation issues for openshift/release#20604. I.e, switches the channel name from `5.2` to `stable` as per ci-built operator registry is using the operator bundle image. Latter provides a slight different channel naming introduced by #734 namely:
```Dockerfile
LABEL operators.operatorframework.io.bundle.channels.v1=stable,stable-5.2
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable
``` 
/cc @sasagarw @jcantrill
=> Use stable as channel name for elasticsearch e2e operator registry

Makefile, hack/test-e2e.sh, hack/testing-olm/test-001-operator-sdk-e2e.sh
This PR addresses preparation issues to resolve openshift/release#20604. In detail it provides a new make target `test-e2e` that leverages the ci managed operator installation.
/cc @sasagarw
=> Add test-e2e target using ci managed operator install

internal/elasticsearch/configmaps_test.go, internal/elasticsearch/configuration_tmpl.go
Query metrics (subject of [LOG-1075](https://issues.redhat.com/browse/LOG-1075)) are by default disabled.
We need to enable them in order to be able to scrape metrics defined by provided query (i.e. query metrics).
/cc @sasagarw 
- JIRA: <https://issues.redhat.com/browse/LOG-1075>
=> LOG-1075: Enable prometheus.query.metrics in ES config

files/dashboards/logging-dashboard-elasticsearch.json
This PR:
- Adds visuals for Index Level Metrics in OCP Logging Dashboard
/cherry-pick 
- JIRA: https://issues.redhat.com/browse/LOG-1680
=> LOG-1680: Add visuals for index level metrics

Makefile, hack/testing-olm/test-001-operator-sdk-e2e.sh, hack/testing-olm/test-200-verify-es-metrics-access.sh, hack/testing-olm/test-657-im-block-autocreate-for-write-suffix.sh
This PR is preparation work for openshift/release#21383 to enable ci-managed operator installs/cleanups during e2e testing. 
=> Skip cleanup for test-e2e ci target

internal/elasticsearch/serviceaccount.go, internal/kibana/serviceaccount.go, internal/manifests/serviceaccount/serviceaccount.go
This PR provides a fix on updating service accounts during reconciliation. I.e. updating serviceaccounts should mutate only Eo provided annotations for now. This ensures that k8s serviceaccount-controller owned fields on SAs namely `ServiceAccount.Secrets` and `ServiceAccount.ImagePullSecrets`.
To address: https://issues.redhat.com/browse/LOG-1589
=> [release-5.2] Fix mutating serviceaccount annotations on updates

Dockerfile, Dockerfile.dev, Dockerfile.in, bundle.Dockerfile
This PR syncs the correct license labels from midstream to upstream.
To address: https://issues.redhat.com/browse/LOG-1750
=> Fix license labels to Apache-2.0

Dockerfile, Dockerfile.dev, Dockerfile.in, dev-meta.yaml, origin-meta.yaml
This PR synchronizes the midstream Dockerfiles (which use the RHEL-8 based golang builder) with upstream.
To address: https://issues.redhat.com/browse/LOG-1750
/cc @igor-karpukhin 
/assign @igor-karpukhin
=> Sync with midstream dockerfiles

bundle/metadata/annotations.yaml
This PR pins in retrospect all upcoming `4.6.z` bundles to be available only on OCP 4.6.z registries.
To address: https://bugzilla.redhat.com/show_bug.cgi?id=2005955 (https://issues.redhat.com/browse/LOG-1751)
More info:
- [Managing OpenShift versions](https://redhat-connect.gitbook.io/certified-operator-guide/ocp-deployment/operator-metadata/bundle-directory/managing-openshift-versions)
- [Slack conversation](https://coreos.slack.com/archives/GGUR75P60/p1631773045120500)
/cc @igor-karpukhin  
/assign @igor-karpukhin
=> Bug 2005955: Limit elasticsearch-operator bundle only on OCP 4.6.z

files/prometheus_alerts.yml
This PR:
- Corrects the URL provided in description of the prometheus rule.
/cc @periklis 
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1983994
=> [release-4.6] Bug 1983994: Prometheus Rule for ElasticsearchClusterNotHealthy description has wrong URL

internal/indexmanagement/reconcile.go
The condition of creating the prune cronjob is changed from `len(policy.Phases.Delete.Namespaces) != 0` to `policy.Phases.Delete.Namespaces != nil`, since the former returned true even when there was no `Namespaces` spec in the CR
/cc 
=> Fix prune condition

go.mod, vendor/modules.txt
This PR provides the missing required go module `k8s.io/utils` as a direct dependency to fix cachito failures.
/cc @btaani 
=> Fix cachito failure for missing required module

internal/elasticsearch/certificates.go
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>
Solving race condition between `GenerateComponentsCerts` and `GenerateKibanaCerts` methods, by adding global mutex.
/cc @jcantrill @igor-karpukhin 
/cherry-pick 
- Bugzilla:
- Github issue:
- JIRA: https://issues.redhat.com/browse/LOG-2093
- Enhancement proposal:
=> LOG-2093: adding a mutex to the functions which call certificate generation

apis/logging/v1/index_management_types.go, bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml, bundle/manifests/logging.openshift.io_elasticsearches.yaml, internal/elasticsearch/certificates.go, internal/indexmanagement/validations_test.go
This PR:
- Updates api to handle empty `pruneNamespaceInterval` field.
/cc @shwetaap 
- JIRA: https://issues.redhat.com/browse/LOG-2120
=> LOG-2120: Updated api to handle empty `pruneNamespaceInterval` field

internal/manifests/configmap/configmap.go, internal/manifests/console/consoleexternalloglink.go, internal/manifests/console/consolelink.go, internal/manifests/cronjob/cronjob.go, internal/manifests/deployment/deployment.go, internal/manifests/persistentvolume/persistentvolumeclaim.go, internal/manifests/prometheusrule/prometheusrule.go, internal/manifests/rbac/clusterrole.go, internal/manifests/rbac/clusterrolebinding.go, internal/manifests/rbac/role.go, internal/manifests/rbac/rolebinding.go, internal/manifests/route/route.go, internal/manifests/secret/secret.go, internal/manifests/securitycontextconstraints/securitycontextconstraints.go, internal/manifests/service/service.go, internal/manifests/serviceaccount/serviceaccount.go, internal/manifests/servicemonitor/servicemonitor.go, internal/manifests/statefulset/statefulset.go
This PR changes the CreateOrUpdate flow. Instead of first creating the object and the attempting to update, the method will attempt to find the object first and if it does not exist, create it.
/cc @sasagarw 
- JIRA: https://issues.redhat.com/browse/LOG-2125
=> Log 2125: CreateOrUpdate Method Flow Fix

files/prometheus_recording_rules.yml
This PR adds additional recording rules to expose some Elasticsearch metrics as operator metrics.
/cc @sasagarw 
- JIRA: https://issues.redhat.com/browse/LOG-2096
=> Log 2096: Elasticsearch Telemetry Metrics

hack/testing-olm-upgrade/resources/cr.yaml
This PR removes the `standard` storage class name for the upgrade test CR. There isn't a `standard` storage class in AWS and thus the upgrade test is unable to properly provision the operator.
/cc @shwetaap 
=> Removing StorageClassName for Upgrade Test CR

controllers/logging/elasticsearch_controller.go, internal/manifests/console/consolelink.go
This PR is a fix for [LOG-1919](https://issues.redhat.com/browse/LOG-1919), it deletes the Kibana console link from the openshift web console after CLO is removed.
- JIRA: https://issues.redhat.com/browse/LOG-1919
=> Deleting Kibana console link after CLO CR deletion

internal/elasticsearch/certificates.go
This PR fixes the case in which the certificates are not regenerated after the CA certificates are created. When the `signing-elasticsearch` secret is deleted, the old certificates are not updated to include the new ones. This PR changes this behavior to regenerate new certificates when this occurs. This PR also organizes the file to make it easier to read.
/cc @sasagarw 
- JIRA: https://issues.redhat.com/browse/LOG-2300
=> Log 2300: Certificates regenerate on CA re-creation

internal/constants/constants.go, internal/elasticsearch/dashboards.go, internal/manifests/configmap/configmap.go
This PR:
- Fixes configmap `grafana-dashboard-elasticsearch` is being created and deleted continously.
/cc @shwetaap 
- JIRA: https://issues.redhat.com/browse/LOG-2308
=> LOG-2308: Update createOrUpdate method for dashboard

apis/logging/v1/index_management_types.go, bundle/manifests/logging.openshift.io_elasticsearches.yaml, config/crd/bases/logging.openshift.io_elasticsearches.yaml, internal/indexmanagement/reconcile.go, internal/indexmanagement/scripts.go
This PR adds the functionality of deleting old indices based on the used disk space of ES nodes.
/cc @sasagarw @shwetaap 
- JIRA: [LOG-1546](https://issues.redhat.com/browse/LOG-1546) and [LOG-2129](https://issues.redhat.com/browse/LOG-2129)
- Enhancement Proposal: https://github.com/openshift/enhancements/blob/master/enhancements/cluster-logging/elasticsearch-percentage-index-management.md
- Implementation details: https://docs.google.com/document/d/1Wtaa3ZWC1kQYAg_xu5YThlLtSZedgxQVvNAWZMaiSWw/edit#
=> Adding percentage-based index management

go.mod, go.sum
This PR addresses CVE-2022-21698 prometheus/client_golang: Denial of service using InstrumentHandlerCounter
Resolves Advisory:
https://github.com/prometheus/client_golang/security/advisories/GHSA-cg3q-j54f-5p7p
/cc @shwetaap 
- JIRA: https://issues.redhat.com/browse/LOG-2407
=> Log 2407: CVE-2022-21698 prometheus/client_golang: Denial of service using InstrumentHandlerCounter

internal/elasticsearch/rbac.go, internal/manifests/rbac/clusterrole.go, internal/manifests/rbac/clusterrolebinding.go
This PR changes the scope of permissions the `prometheus-k8s` ServiceAccount can use by making a `Role`/`RoleBinding` instead of a `ClusterRole`/`ClusterRoleBinding`.
/cc @btaani 
- JIRA: https://issues.redhat.com/browse/LOG-2474
=> Log 2474: Changing prometheus-k8s permissions scope

internal/types/elasticsearch/types.go
This PR:
- updates the `IndexMapperSettings` struct to parse string while GET request.
- currently `settings.index.mapper.dynamic` is parsed wrongly since the json value is returned as string during GET request. However, during a PUT request this value should be a bool.
/cc @periklis 
- JIRA: https://issues.redhat.com/browse/LOG-2463
=> LOG-2463: Elasticsearch operator repeatedly prints error message when checking indices

apis/logging/v1/index_management_types.go, bundle/manifests/logging.openshift.io_elasticsearches.yaml, config/crd/bases/logging.openshift.io_elasticsearches.yaml, internal/indexmanagement/validations.go
This PR removes the support of `y` and `M` time units that are specified in Elasticsearch CRD (`yMwdhHms`).
/cc @sasagarw 
- JIRA: [LOG-2418](https://issues.redhat.com/browse/LOG-2418)
=> Remove support of 'years' and 'months' timeunits from CRD

go.mod, go.sum, internal/elasticsearch/certificates.go, vendor/k8s.io/utils/pointer/pointer.go, vendor/k8s.io/utils/strings/slices/slices.go, vendor/modules.txt
Cherry-pick of #884 with additional dependency update. Supersedes #886.
The dependency is updated to the same version as used in `master`.
=> [release-5.4] LOG-2154: Check attributes of subject for component certificates

apis/logging/v1/elasticsearch_types.go, bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml, config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml, internal/manifests/cronjob/cronjob.go
The present ClusterServiceVersion is still pointing that the Elasticsearch custom resources owns resources from the deprecated API group `batchv1beta1` namely `Cronjob`. However in #813 we switched from `batchv1beta1` to `batchv1`. This PR complements the missing bits in the ClusterServiceVersion.
__Note__: Requires manual backport to release-5.4.
/cc @Red-GV 
- JIRA: [LOG-2656](https://issues.redhat.com/browse/LOG-2656) and [LOG-2618](https://issues.redhat.com/browse/LOG-2618)
=> LOG-2656: Fix csv owned resources to point to batchv1 cronjob

internal/elasticsearch/service_monitor.go, internal/elasticsearch/service_monitor_test.go
This PR provides a fix that omits merging the Elasticsearch CR into the Elasticsearch ServiceMonitor labels selectors, e.g. the jaeger operator creates Elasticsearch CRs with custom labels (See [jaeger-operator](https://github.com/jaegertracing/jaeger-operator/blob/1a76367a3771c96806309a071ca0ef72d95796e9/pkg/storage/elasticsearch.go#L177-L188}).
ServiceMonitor for ES via Jaeger CR showing up again:
/cc @Red-GV 
/cherry-pick release-5.4
- JIRA:  https://issues.redhat.com/browse/LOG-2693
=> LOG-2693: Fix matching labels selectors for servicemonitors

internal/elasticsearch/service_monitor.go, internal/elasticsearch/service_monitor_test.go
Manual cherry-pick of #894 as per #895 failing to resolve module dependencies, i.e. main is using `prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1` vs. release-5.4 using `coreos/prometheus-operator/pkg/apis/monitoring/v1`
/cc @Red-GV 
- JIRA: https://issues.redhat.com/browse/LOG-2696
=> [release-5.4] LOG-2696: Fix matching labels selectors for servicemonitors

internal/kibana/reconciler.go
The following PR enables availability healthchecks of Kibana using for example prometheus blackbox exporter.
- JIRA: https://issues.redhat.com/browse/LOG-2728
=> LOG-2728: Allow blackbox availability healthchecks for Kibana

Makefile, internal/kibana/kibana_test.go, internal/kibana/reconciler.go
The operator uses the ImageStream`openshift/oauth-proxy` to select an image to use for the proxy used in the Kibana deployment.
This PR updates the logic used in selecting the right image for the right context, by including [referencePolicy](https://docs.openshift.com/container-platform/4.10/rest_api/image_apis/imagestream-image-openshift-io-v1.html#spec-tags-referencepolicy) in the decision making.
- JIRA: [LOG-2679](https://issues.redhat.com/browse/LOG-2764)
=> LOG-2679: Fix Elasticsearch operator not respecting referencePolicy when selecting oauth-proxy image

internal/kibana/route.go
This PR removes the CA certificate from the Kibana Route as it seems unnecessary. This change comes as a result of the following user reported issue [LOG-2661](https://issues.redhat.com/browse/LOG-2661)
/cc @xperimental  
- JIRA: [LOG-2661](https://issues.redhat.com/browse/LOG-2661)
=> LOG-2661: Remove CA certificate from Kibana Route

internal/elasticsearch/common.go, internal/elasticsearch/common_test.go, internal/indexmanagement/reconcile.go, internal/indexmanagement/reconcile_test.go, internal/kibana/kibana_test.go, internal/kibana/reconciler.go, internal/kibana/reconciler_test.go, internal/manifests/pod/build.go, internal/utils/utils.go
This PR adds security contexts to ES operands' pods and containers, so as to be compliant with the [PSA](https://kubernetes.io/docs/concepts/security/pod-security-admission/)'s `restricted` policy
- JIRA: [LOG-2737](https://issues.redhat.com/browse/LOG-2737)
=> LOG-2737: Add security context to operands

internal/elasticsearch/common.go, internal/elasticsearch/configmaps.go, internal/elasticsearch/rbac.go, internal/elasticsearch/reconciler.go, internal/elasticsearch/service_monitor.go, internal/elasticsearch/service_monitor_test.go, internal/elasticsearch/serviceaccount.go, internal/manifests/configmap/configmap.go, internal/manifests/secret/secret.go, internal/manifests/serviceaccount/serviceaccount.go, test/e2e/elasticsearch_metric_test.go
For legacy reasons the elasticsearch-operator assumes that `Elasticsearch` and owned `ServiceMonitor` resources installed **only** on `openshift-` namespaces or those annotated with `openshift.io/cluster-monitoring: true`. In both case the cluster-monitoring stack takes responsibility to reconcile the `ServiceMonitor` resources for the cluster-monitoring Prometheus. In detail ServiceMonitor endpoints used the `prometheus-k8s`'s serviceaccount token to scrape metrics from elasticsearch and elasticsearch-proxy. This is the legacy and nowadays not-recommended practice that is still sustained in OCP's cluster-monitoring for compatibility reason (i.e. prometheus CR `ArbitraryFSAccessThroughSMsConfig.Deny: false`)
Moving forward in time with the addition of [User Workload Monitoring]() in OCP …
=> LOG-2732: Fix ES servicemonitor for user-workload-monitoring

internal/elasticsearch/deployment.go
This PR ensures that the new pods created by the deployment are in a ready state before updating the next deployment. Without this, there is a chance that the cluster does not return to the `green` state since the master node quorum is probably not observed.
=> Checking if the pod containers are ready before deployment update

Dockerfile, Dockerfile.dev, Dockerfile.in, dev-meta.yaml, go.mod, origin-meta.yaml
This PR updates release to go 1.17 to address CVE-2022-30631.
/assign @jcantrill @periklis 
Links
- JIRA: https://issues.redhat.com/browse/LOG-2901
=> LOG-2901: CVE-2022-30631 golang: compress/gzip: stack exhaustion in Reader.Read

bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml, config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
This PR adds the `operators.openshift.io/valid-subscription` annotation to the operator metadata.
- JIRA: https://issues.redhat.com/browse/LOG-2924
=> LOG-2924: Adding valid subscription annotation to metadata

controllers/logging/kibana_controller.go, internal/kibana/route.go, internal/manifests/console/build.go, internal/manifests/console/consoleexternalloglink.go
This PR adds a manual deletion of the `consoleexternalloglinks.console.openshift.io/kibana` resource when the `Kibana` resource is deleted.
/cc @periklis 
/assign @xperimental 
- JIRA: https://issues.redhat.com/browse/LOG-2993
=> Clean up ConsoleExternalLogLink when Kibana resource is deleted

internal/elasticsearch/configmaps.go
Small amendment to #903 to allow deleting the configmap when ES CR gets deleted
/cherry-pick release-5.4
=> Add missing owner for ca bundle configmap

controllers/logging/kibana_controller.go, internal/kibana/route.go, internal/manifests/console/build.go, internal/manifests/console/consoleexternalloglink.go
Manual backport of #936  
/cc @periklis 
- JIRA: [LOG-3053](https://issues.redhat.com/browse/LOG-3053)
=> [release-5.5] Clean up ConsoleExternalLogLink when Kibana resource is deleted

controllers/logging/kibana_controller.go, internal/kibana/route.go, internal/manifests/console/build.go, internal/manifests/console/consoleexternalloglink.go
Manual backport of #936 
/cc @periklis 
- JIRA: [LOG-3054](https://issues.redhat.com/browse/LOG-3054)
=> [release-5.4] Clean up ConsoleExternalLogLink when Kibana resource is deleted

bundle/metadata/properties.yaml
This PR:
Updates the max supported OCP version to 4.12
https://issues.redhat.com/browse/LOG-3123
=> LOG-3123: fix OCP max version

bundle/metadata/properties.yaml
* updates maxOpenShiftVersion to 4.12
https://issues.redhat.com/browse/LOG-3119
=> LOG-3119: Update max OCP to 4.12

internal/elasticsearch/serviceaccount.go, internal/manifests/secret/secret.go
The reconciliation for the `elasticsearch-metrics-token` secret currently overwrites both annotations and data for the secret. Because the secret data is not generated by the operator but by Kubernetes itself, this results in the operator deleting the data and Kubernetes adding the data again in an endless cycle (approximately 1Hz :wink:).
This PR updates the reconciliation code to only look at the annotations of the secret.
This is a port of #946 .
- JIRA: [LOG-3161](https://issues.redhat.com//browse/LOG-3161)
=> LOG-3161: Do not overwrite token secret data

internal/elasticsearch/serviceaccount.go, internal/manifests/secret/secret.go
The reconciliation for the `elasticsearch-metrics-token` secret currently overwrites both annotations and data for the secret. Because the secret data is not generated by the operator but by Kubernetes itself, this results in the operator deleting the data and Kubernetes adding the data again in an endless cycle (approximately 1Hz :wink:).
This PR updates the reconciliation code to only look at the annotations of the secret.
- JIRA: [LOG-3138](https://issues.redhat.com//browse/LOG-3138)
=> LOG-3138: Do not overwrite token secret data

Dockerfile, Dockerfile.dev, Dockerfile.in, dev-meta.yaml, go.mod, origin-meta.yaml
Updates Go version used for building to 1.19.
Not really sure about the different image repository used for `Dockerfile` (`registry.ci.openshift.org/ocp/builder`) and `Dockerfile.dev` (`registry.ci.openshift.org/openshift/release`). The images seem to be different as well.
- JIRA: [LOG-3148](https://issues.redhat.com//browse/LOG-3148)
=> LOG-3148: Update to Go 1.19

.bingo/Variables.mk, .bingo/operator-sdk.mod, .bingo/operator-sdk.sum, .bingo/variables.env
Upgrade local tool operator-sdk to v1.24.1 to fix `make olm-deploy` install the temporary registry on OCP 4.12 with restricted PSA applied.
=> Upgrade operator-sdk to v1.24.1

apis/logging/v1/groupversion_info.go, bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/logging/kibana_controller.go, internal/constants/constants.go, internal/elasticsearch/common.go, internal/kibana/kibana_test.go, internal/kibana/reconciler.go, internal/kibana/reconciler_test.go, internal/utils/comparators/envvars.go, internal/utils/utils.go
This PR fixes the Kibana Oauth authentication expiration by synchronizing the Kibana authentication cookie expiration time with the OCP OAuth's `accessTokenInactivityTimeout`.
/cc @periklis 
- JIRA: [LOG-3129](https://issues.redhat.com/browse/LOG-3129)
=> LOG-3129: Fix kibana oauth cookie expiration issue

Makefile, olm_deploy/scripts/operator-install.sh
This PR:
* allows the deploy channel to be passed in.  Motivation is we should make master 'stable' and during branch cut it "should" facilitate the transition between the 2 branches
=> allow changing deploy channel

bundle/metadata/properties.yaml
The `release-5.6` branch will support up to and including OCP 4.13 based on our support policy.
/cc @xperimental @jcantrill 
- JIRA: [LOG-3584](https://issues.redhat.com//browse/LOG-3584)
=> [release-5.6] Bump bundle OCP max version property to 4.14

bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml, config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
This changes the generated bundle to include a `skipRange` attribute that limits direct updates to only be able from 5.5 onwards.
- JIRA: [LOG-4041](https://issues.redhat.com//browse/LOG-4041)
=> LOG-4041: Update skipRange to allow updating from 5.5 onwards

internal/elasticsearch/configmaps_test.go, internal/elasticsearch/configuration_tmpl.go
Follow-up on [LOG-1899](https://issues.redhat.com//browse/LOG-1899) to increase the header size to allow operating on customer clusters with a huge amount of namespaces (>8000).
=> LOG-4243: Bump ES default http.max_header_size to 512kb

internal/elasticsearch/certificates.go
Removes a duplicate CA validation check when expired that blocked CA certificate rotation.
- JIRA: LOG-4303
=> Fix invalid CA certificate rotation on expiry

bundle/metadata/properties.yaml
Bump Max OpenShift Version to `4.16` to keep existing installations from raising `IncompatibleOperatorsInstalled` alerts.
=> LOG-5272: Bump max OpenShift version to 4.16

go.mod, internal/manifests/serviceaccount/serviceaccount.go
Fix continuously generating secrets in the Elasticsearch, Kibana instance namespace on OCP 4.16
/cc @xperimental @JoaoBraveCoding 
- JIRA: [LOG-5776](https://issues.redhat.com//browse/LOG-5776)
=> [release-5.8] LOG-5776: Skip overriding annotations provided by other controllers

bundle/manifests/elasticsearch-operator.clusterserviceversion.yaml, config/manifests/bases/elasticsearch-operator.clusterserviceversion.yaml
Adapt support statement to make it clear that OCP Elasticsearch Operator will be available on all supported OCP versions until November 2025.
/cc @xperimental @JoaoBraveCoding
=> Fix support statement until catalog removal date

bundle/metadata/properties.yaml
Follow-up on #1015 to support installs for related products up to OCP cluster upgrades to 4.18
/cc @xperimental @JoaoBraveCoding
=> Bump max openshift version 4.18
